//HintName: TestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients.Nested;

/// <summary>
/// Represents a HubClient for the <see cref = "ITestHubClient"/> interface.
/// </summary>
public class TestHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "examples";
    public TestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeUpdate of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<IEnumerable<CustomTypeDto>, Task>? OnReceiveCustomTypeUpdate = default;
    private Task ReceiveCustomTypeUpdateHandler(IEnumerable<CustomTypeDto> customTypes)
    {
        return OnReceiveCustomTypeUpdate?.Invoke(customTypes) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveFooUpdate of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<string, int, Task>? OnReceiveFooUpdate = default;
    private Task ReceiveFooUpdateHandler(string bar, int bass)
    {
        return OnReceiveFooUpdate?.Invoke(bar, bass) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNormalTypeWithSpecificAttributeApplied of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<string, int, Task>? OnReceiveNormalTypeWithSpecificAttributeApplied = default;
    private Task ReceiveNormalTypeWithSpecificAttributeAppliedHandler(string bazz, int buzz)
    {
        return OnReceiveNormalTypeWithSpecificAttributeApplied?.Invoke(bazz, buzz) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveWithArbitraryAttribute of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<int, Task>? OnReceiveWithArbitraryAttribute = default;
    private Task ReceiveWithArbitraryAttributeHandler(int blub)
    {
        return OnReceiveWithArbitraryAttribute?.Invoke(blub) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendClientToServerNoReturnType on the <see cref = "ITestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public Task InvokeSendClientToServerNoReturnTypeAsync(string rick, int age, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendClientToServerNoReturnType", rick, age, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the SendClientToServerWithReturnType on the <see cref = "ITestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public Task<string> InvokeSendClientToServerWithReturnTypeAsync(string morty, bool partOfMission, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string>("SendClientToServerWithReturnType", morty, partOfMission, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<IEnumerable<CustomTypeDto>>("ReceiveCustomTypeUpdate", ReceiveCustomTypeUpdateHandler);
	    _hubConnection?.On<string, int>("ReceiveFooUpdate", ReceiveFooUpdateHandler);
	    _hubConnection?.On<string, int>("ReceiveNormalTypeWithSpecificAttributeApplied", ReceiveNormalTypeWithSpecificAttributeAppliedHandler);
	    _hubConnection?.On<int>("ReceiveWithArbitraryAttribute", ReceiveWithArbitraryAttributeHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}