//HintName: SignalRClientServiceRegistration.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Clients;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.DependencyInjection;
using SignalRGen.Generator.Client.Configuration;

#nullable enable

namespace SignalRGen.Generator.Client.Extensions.DependencyInjection;

public static class SignalRClientServiceRegistration
{
    /// <summary>
    /// Creates the base configuration for all registered Hubs. The Hubs you want to use must be registered with the appropriate `With{...}` call.
    /// </summary>
    /// <param name = "services">The services available in the application.</param>
    /// <param name = "generalConfiguration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "SignalRHubServiceCollection"/> to register the specified Hub.</returns>
    public static SignalRHubServiceCollection AddSignalRHubs(this IServiceCollection services, Action<SignalROptions> generalConfiguration)
    {
        ArgumentNullException.ThrowIfNull(generalConfiguration);
        var config = new SignalROptions();
        generalConfiguration.Invoke(config);
        return new SignalRHubServiceCollection(services, config);
    }

    /// <summary>
    /// Registers the <see cref = "TestHubClient"/> in the <see cref = "ServiceCollection"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// By default the <see cref = "TestHubClient"/> is registered with <see cref = "ServiceLifetime"/> singleton.
    /// </para>
    /// If no <see cref = "IRetryPolicy"/> is configured for the <see cref = "HubConnectionBuilder"/> a default retry policy will be used.
    /// <list type="bullet">
    ///     <item>
    ///         Every second - 10 attempts
    ///     </item>
    ///     <item>
    ///         Every 3 seconds - 5 attempts
    ///     </item>
    ///     <item>
    ///         Every 10 seconds - 2 attempts
    ///     </item>
    /// </list>
    /// </remarks>
    /// <param name = "services">The <see cref = "SignalRHubServiceCollection"/> to register the Hub.</param>
    /// <param name = "configuration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "SignalRHubServiceCollection"/> to register additional Hubs.</returns>
    public static SignalRHubServiceCollection WithTestHubClient(this SignalRHubServiceCollection services, Action<HubClientOptions>? configuration = null)
    {
        ArgumentNullException.ThrowIfNull(services);
        var config = new HubClientOptions();
        configuration?.Invoke(config);
        services.Services.Add(new ServiceDescriptor(typeof(TestHubClient), factory: _ =>
        {
            var hubConnectionBuilder = new HubConnectionBuilder().WithUrl(new Uri(services.GeneralConfiguration.HubBaseUri, TestHubClient.HubUri)).WithAutomaticReconnect(DefaultRetrySteps.ToArray());
            config.HubConnectionBuilderConfiguration?.Invoke(hubConnectionBuilder);
            return new TestHubClient(hubConnectionBuilder);
        }, config.HubClientLifetime));
        return services;
    }

    private static IEnumerable<TimeSpan> DefaultRetrySteps
    {
        get
        {
            var retrySteps = Enumerable.Repeat(TimeSpan.FromSeconds(1), 10);
            retrySteps = retrySteps.Concat(Enumerable.Repeat(TimeSpan.FromSeconds(3), 5));
            retrySteps = retrySteps.Concat(Enumerable.Repeat(TimeSpan.FromSeconds(10), 2));
            return retrySteps;
        }
    }
}