//HintName: TestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Generator;
using SignalRGen.Generator.Tests.TestData;
using Microsoft.AspNetCore.SignalR.Client;
using SignalRGen.Clients;

#nullable enable

namespace SignalRGen.Generator;

/// <summary>
/// Represents a HubClient for the <see cref = "ITestHubClient"/> interface.
/// </summary>
public class TestHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "examples";
    public TestHubClient(IHubConnectionBuilder hubConnectionBuilder) : base(hubConnectionBuilder)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeUpdate of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<IEnumerable<CustomTypeDto>, Task>? OnReceiveCustomTypeUpdate = default;
    private Task ReceiveCustomTypeUpdateHandler(IEnumerable<CustomTypeDto> customTypes)
    {
        return OnReceiveCustomTypeUpdate?.Invoke(customTypes) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveFooUpdate of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<string, int, Task>? OnReceiveFooUpdate = default;
    private Task ReceiveFooUpdateHandler(string bar, int bass)
    {
        return OnReceiveFooUpdate?.Invoke(bar, bass) ?? Task.CompletedTask;
    }
    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<IEnumerable<CustomTypeDto>>("ReceiveCustomTypeUpdate", ReceiveCustomTypeUpdateHandler);
	    _hubConnection?.On<string, int>("ReceiveFooUpdate", ReceiveFooUpdateHandler);
    }
}