//HintName: HubClientAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

#nullable enable
namespace SignalRGen.Generator;
/// <summary>
/// Marker Attribute for a HubClient.
/// </summary>
[AttributeUsage(AttributeTargets.Interface)]
public sealed class HubClientAttribute : Attribute
{
    public string? HubName { get; init; }
    public required string HubUri { get; init; }
}