//HintName: SignalROptions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace SignalRGen.Generator.Client.Configuration;

/// <summary>
/// Encapsulates the options to configure a SignalR Client.
/// </summary>
public class SignalROptions
{
    /// <summary>The base <see cref="Uri"/> for the SignalR Client.</summary>
    /// <remarks>This <see cref="Uri"/> will be used for every `With...` Hub defined.</remarks>
    public Uri HubBaseUri { get; set; } = default!;
}