//HintName: ExampleHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Generator;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Example.Contracts;

/// <summary>
/// Represents a HubClient for the <see cref = "IExampleHubClient"/> interface.
/// </summary>
public class ExampleHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "example";
    public ExampleHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method CommonMethod of the <see cref = "IExampleHubClient"/> gets invoked.
    /// </summary>
    public Func<string, Task>? OnCommonMethod = default;
    private Task CommonMethodHandler(string param1)
    {
        return OnCommonMethod?.Invoke(param1) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method CommonMethod of the <see cref = "IExampleHubClient"/> gets invoked.
    /// </summary>
    public Func<int, Task>? OnCommonMethod = default;
    private Task CommonMethodHandler(int param1)
    {
        return OnCommonMethod?.Invoke(param1) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveExampleCountUpdate of the <see cref = "IExampleHubClient"/> gets invoked.
    /// </summary>
    public Func<int, Task>? OnReceiveExampleCountUpdate = default;
    private Task ReceiveExampleCountUpdateHandler(int count)
    {
        return OnReceiveExampleCountUpdate?.Invoke(count) ?? Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string>("CommonMethod", CommonMethodHandler);
	    _hubConnection?.On<int>("CommonMethod", CommonMethodHandler);
	    _hubConnection?.On<int>("ReceiveExampleCountUpdate", ReceiveExampleCountUpdateHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}