//HintName: SignalRHubServiceCollection.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SignalRGen.Generator.Client.Configuration;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.DependencyInjection;

#nullable enable
namespace SignalRGen.Generator.Client.Extensions.DependencyInjection;
public record SignalRHubServiceCollection(IServiceCollection Services, SignalROptions GeneralConfiguration);