using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SignalRGen.Generator.Sources;

internal static class ClientToServerMethodAttributeSource
{
    internal static SourceText GetSource()
    {
        var template =
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            using System;

            #nullable enable

            namespace SignalRGen.Generator;

            [AttributeUsage(AttributeTargets.Method)]
            public sealed class ClientToServerMethodAttribute : Attribute
            {
            }
            """;
        
        return SourceText.From(template, Encoding.UTF8);
    }
}