using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class HubClientOptionsSource
{
    internal static SourceText GetSource()
    {
        const string template = $$"""
                                  {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}

                                  using Microsoft.AspNetCore.SignalR.Client;
                                  using Microsoft.Extensions.DependencyInjection;

                                  #nullable enable
                                  namespace SignalRGen.Generator.Client.Configuration;

                                  /// <summary>
                                  /// Encapsulates the options to configure a SignalR Hub Client.
                                  /// </summary>
                                  public class HubClientOptions
                                  {
                                      /// <summary>The configuration used to setup the <see cref = "HubConnectionBuilder"/> that will be used to build to the <see cref = "HubConnection"/>.</summary>
                                      public Action<IHubConnectionBuilder> HubConnectionBuilderConfiguration { get; set; } = default !;
                                      
                                      /// <summary>The <see cref = "ServiceLifetime"/> used to register the Hub Client with the DI container.</summary>
                                      public ServiceLifetime HubClientLifetime { get; set; } = ServiceLifetime.Singleton;
                                  }
                                  """;

        return SourceText.From(template, Encoding.UTF8);
    }
}