using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SignalRGen.Generator.Common;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class HubClientSource
{
    private const string HubClientTemplate = """
                                             //------------------------------------------------------------------------------
                                             // <auto-generated>
                                             //     This code was generated by a tool.
                                             //
                                             //     Changes to this file may cause incorrect behavior and will be lost if
                                             //     the code is regenerated.
                                             // </auto-generated>
                                             //------------------------------------------------------------------------------

                                             {~{usings}~}

                                             #nullable enable

                                             namespace {~{namespaceName}~};

                                             /// <summary>
                                             /// Represents a HubClient for the <see cref = "{~{hubClientInterface}~}"/> interface.
                                             /// </summary>
                                             public class {~{hubName}~} : HubClientBase, IHubClient
                                             {
                                                 public static string HubUri { get; } = "{~{hubUri}~}";
                                                 public {~{hubName}~}(IHubConnectionBuilder hubConnectionBuilder) : base(hubConnectionBuilder)
                                                 {
                                                 }
                                                 
                                             {~{serverToClientMethods}~}
                                             
                                             {~{clientToServerMethods}~}
                                             
                                                 
                                                 protected override void RegisterHubMethods()
                                                 {
                                                 {~{onMethods}~}
                                                 }
                                             }
                                             
                                             private void ValidateHubConnection()
                                             {
                                                 if (_hubConnection is null)
                                                 {
                                                     throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
                                                 }
                                             }
                                             """;
    private const string ServerToClientMethodTemplate = """
                                                            /// <summary>
                                                            /// Is invoked whenever the client method {~{identifier}~} of the <see cref = "{~{hubClientInterface}~}"/> gets invoked.
                                                            /// </summary>
                                                            public Func<{~{parameterTypes}~}, Task>? On{~{identifier}~} = default;
                                                            private Task {~{identifier}~}Handler({~{parameterList}~})
                                                            {
                                                                return On{~{identifier}~}?.Invoke({~{parameters}~}) ?? Task.CompletedTask;
                                                            }
                                                        """;

    private const string ClientToServerMethodTemplate =
        """
            public {~{returnType}~} Invoke{~{identifier}~}Async({~{parameterList}~}, CancellationToken ct = default)
            {
                ValidateHubConnection();
                return _hubConnection!.InvokeAsync{~{genericReturnType}~}("{~{identifier}~}", {~{parameters}~}, cancellationToken: ct);
            }
        """;
    private const string OnMethodTemplate = """
                                                _hubConnection?.On<{~{parameterTypes}~}>("{~{identifier}~}", {~{identifier}~}Handler);
                                            """;

    internal static SourceText GetSourceText(HubClientToGenerate hubClientToGenerate)
    {
        var allUsings =
            hubClientToGenerate.Usings
                .Append(new CacheableUsingDeclaration("using Microsoft.AspNetCore.SignalR.Client;"))
                .Append(new CacheableUsingDeclaration($"using {hubClientToGenerate.InterfaceNamespace};"));
        var usings = string.Join("\n", allUsings.Select(u => u.UsingNamespace));

        var serverToClientMethods = hubClientToGenerate.ServerToClientMethods.Select(method =>
            {
                var parameterTypes = string.Join(", ", method.Parameters.Select(p => p.Type));
                var parameterList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                var parameters = string.Join(", ", method.Parameters.Select(p => p.Name));

                return ServerToClientMethodTemplate
                    .Replace("{~{hubClientInterface}~}", hubClientToGenerate.InterfaceName)
                    .Replace("{~{identifier}~}", method.Identifier)
                    .Replace("{~{parameterTypes}~}", parameterTypes)
                    .Replace("{~{parameterList}~}", parameterList)
                    .Replace("{~{parameters}~}", parameters);
            })
            .ToArray();

        var clientToServerMethods = hubClientToGenerate.ClientToServerMethods.Select(method =>
        {
            var parameterTypes = string.Join(", ", method.Parameters.Select(p => p.Type));
            var parameterList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var parameters = string.Join(", ", method.Parameters.Select(p => p.Name));

            var template = ClientToServerMethodTemplate.Replace("{~{hubClientInterface}~}", hubClientToGenerate.InterfaceName)
                .Replace("{~{identifier}~}", method.Identifier)
                .Replace("{~{parameterTypes}~}", parameterTypes)
                .Replace("{~{parameterList}~}", parameterList)
                .Replace("{~{parameters}~}", parameters)
                .Replace("{~{returnType}~}", method.ReturnType)
                .Replace("{~{genericReturnType}~}", method.ReturnType.Replace("Task", ""));

            return template;
        });

        var onMethods = hubClientToGenerate.ServerToClientMethods
            .Select(method =>
            {
                var parameterTypes = string.Join(", ", method.Parameters.Select(p => p.Type));

                return OnMethodTemplate.Replace("{~{identifier}~}", method.Identifier)
                    .Replace("{~{parameterTypes}~}", parameterTypes);
            })
            .ToArray();

        var template = HubClientTemplate
            .Replace("{~{usings}~}", usings)
            .Replace("{~{namespaceName}~}", "SignalRGen.Generator")
            .Replace("{~{hubName}~}", hubClientToGenerate.HubName)
            .Replace("{~{hubUri}~}", hubClientToGenerate.HubUri)
            .Replace("{~{hubClientInterface}~}", hubClientToGenerate.InterfaceName)
            .Replace("{~{serverToClientMethods}~}", string.Join("\n", serverToClientMethods))
            .Replace("{~{clientToServerMethods}~}", string.Join("\n", clientToServerMethods))
            .Replace("{~{onMethods}~}", string.Join("\n\t", onMethods));


        return SourceText.From(template, Encoding.UTF8);
    }
}