using System.Text;
using Microsoft.CodeAnalysis.Text;
using SignalRGen.Generator.Common;

namespace SignalRGen.Generator.Sources;

internal static class HubClientBaseSource
{
    private         const string HubClientBaseTemplate = $$"""
                                  {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}

                                  using Microsoft.AspNetCore.SignalR.Client;
                                  using Microsoft.AspNetCore.Http.Connections.Client;

                                  #nullable enable
                                  namespace {~{namespaceName}~};

                                  /// <summary>
                                  /// Base class for generated HubClients.
                                  /// </summary>
                                  /// <remarks>
                                  /// This base is partial to allow for extensions for all clients.
                                  /// Be aware that any extended behavior might result in the need to rewrite the DisposeAsync.
                                  /// </remarks>
                                  public abstract partial class HubClientBase : IAsyncDisposable
                                  {
                                      protected HubConnection? _hubConnection;

                                      private readonly Action<IHubConnectionBuilder>?
                                          _hubConnectionBuilderConfiguration;
                                          
                                      private Action<HttpConnectionOptions>?
                                          _httpConnectionOptions;
                                      
                                      private readonly Uri _baseHubUri;
                                      private bool _isRegistered;
                                      private readonly HubConnectionBuilder _hubConnectionBuilder;
                                      
                                      /// <summary>
                                      /// Gets invoked each time the Closed event from the underlying <see cref = "HubConnection"/> occurs.
                                      /// </summary>
                                      public Func<Exception?, Task>? Closed;
                                      
                                      /// <summary>
                                      /// Gets invoked each time the Reconnecting event from the underlying <see cref = "HubConnection"/> occurs.
                                      /// </summary>
                                      public Func<Exception?, Task>? Reconnecting;
                                      
                                      /// <summary>
                                      /// Gets invoked each time the reconnected event from the underlying <see cref = "HubConnection"/> occurs.
                                      /// </summary>
                                      public Func<Task>? Reconnected;
                                      
                                      protected HubClientBase(
                                        Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
                                        Uri baseHubUri,
                                        Action<HttpConnectionOptions>? httpConnectionOptions)
                                      {
                                          _hubConnectionBuilderConfiguration = hubConnectionBuilderConfiguration;
                                          _baseHubUri = baseHubUri;
                                          _httpConnectionOptions = httpConnectionOptions;
                                          _hubConnectionBuilder = new HubConnectionBuilder();
                                      }

                                      /// <summary>
                                      /// Asynchronously starts the underlying <see cref = "HubConnection"/> and registers the event callbacks for the SignalR client methods.
                                      /// </summary>
                                      /// <param name="queryStrings">A dictionary of query string parameters to be added to the connection URL.</param>
                                      /// <param name="headers">A dictionary of headers to be included in the SignalR client's HTTP requests.</param>
                                      /// <param name = "cancellationToken">A <see cref = "CancellationToken"/> to cancel the start of the <see cref = "HubConnection"/>.</param>
                                      public virtual Task StartAsync(
                                        Dictionary<string, string>? queryStrings = null,
                                        Dictionary<string, string>? headers = null,
                                        CancellationToken cancellationToken = default)
                                      {
                                          AddHeaders(headers);      
                                      
                                          _hubConnectionBuilder
                                              .WithUrl(AddParametersToUri(queryStrings, _baseHubUri), _httpConnectionOptions!)
                                              .WithAutomaticReconnect(DefaultRetrySteps.ToArray());
                                          _hubConnectionBuilderConfiguration?.Invoke(_hubConnectionBuilder);
                                          _hubConnection ??= _hubConnectionBuilder.Build();
                                          if (!_isRegistered)
                                          {
                                              _hubConnection.Closed += Closed;
                                              _hubConnection.Reconnected += OnReconnected;
                                              _hubConnection.Reconnecting += Reconnecting;
                                              RegisterHubMethods();
                                              _isRegistered = true;
                                          }

                                          return _hubConnection.State == HubConnectionState.Disconnected ? _hubConnection.StartAsync(cancellationToken) : Task.CompletedTask;
                                      }

                                      /// <summary>
                                      /// Asynchronously stops the underlying <see cref = "HubConnection"/>.
                                      /// </summary>
                                      /// <param name = "cancellationToken">A <see cref = "CancellationToken"/> to cancel the stop of the <see cref = "HubConnection"/>.</param>
                                      public virtual Task StopAsync(CancellationToken cancellationToken = default)
                                      {
                                          return _hubConnection is null ? Task.CompletedTask : _hubConnection.StopAsync(cancellationToken);
                                      }

                                      protected abstract void RegisterHubMethods();
                                      private Task OnReconnected(string? connectionId)
                                      {
                                          return Reconnected is not null ? Reconnected.Invoke() : Task.CompletedTask;
                                      }
                                      
                                      /// <summary>
                                      /// Hook for generated client-to-server Invoke methods.
                                      /// The default implementation invokes the underlying HubConnection.
                                      /// Test fakes override this to short-circuit network calls.
                                      /// </summary>
                                      /// <param name="methodName">Hub method name.</param>
                                      /// <param name="args">Arguments serialized by SignalR.</param>
                                      /// <param name="cancellationToken">Cancellation token.</param>
                                      /// <exception cref="InvalidOperationException">When the hub connection was not started.</exception>
                                      protected virtual Task InvokeCoreAsync(string methodName, object?[] args, CancellationToken cancellationToken)
                                      {
                                          if (_hubConnection is null)
                                          {
                                              throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
                                          }
                                      
                                          // Use InvokeCoreAsync to avoid overload churn.
                                          return _hubConnection.InvokeCoreAsync(methodName, args, cancellationToken);
                                      }
                                  
                                      /// <summary>
                                      /// Hook for generated client-to-server Invoke methods that return a value.
                                      /// The default implementation invokes the underlying HubConnection and returns the result.
                                      /// Test fakes override this to short-circuit network calls and return arranged results.
                                      /// </summary>
                                      /// <typeparam name="TResult">The result type returned by the Hub method.</typeparam>
                                      /// <param name="methodName">Hub method name.</param>
                                      /// <param name="args">Arguments serialized by SignalR.</param>
                                      /// <param name="cancellationToken">Cancellation token.</param>
                                      /// <exception cref="InvalidOperationException">When the hub connection was not started.</exception>
                                      protected virtual Task<TResult> InvokeCoreAsync<TResult>(string methodName, object?[] args, CancellationToken cancellationToken)
                                      {
                                          if (_hubConnection is null)
                                          {
                                              throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
                                          }
                                          return _hubConnection.InvokeCoreAsync<TResult>(methodName, args, cancellationToken);
                                      }
                                  
                                  

                                      /// <summary>
                                      /// Releases resources for the underlying <see cref = "HubConnection"/>.
                                      /// </summary>
                                      /// <returns>A <see cref = "ValueTask"/> that completes when resources have been released.</returns>
                                      public ValueTask DisposeAsync()
                                      {
                                          if (_hubConnection is null)
                                          {
                                              return ValueTask.CompletedTask;
                                          }

                                          _hubConnection.Closed -= Closed;
                                          _hubConnection.Reconnected -= OnReconnected;
                                          _hubConnection.Reconnecting -= Reconnecting;
                                          return _hubConnection.DisposeAsync();
                                      }
                                      
                                      private void AddHeaders(Dictionary<string, string>? headers)
                                      {
                                          if (headers is null || headers.Count == 0) return;
                                      
                                          var originalOptions = _httpConnectionOptions;
                                      
                                          _httpConnectionOptions = options =>
                                          {
                                              originalOptions?.Invoke(options);
                                      
                                              options.Headers ??= new Dictionary<string, string>();
                                      
                                              foreach (var header in headers)
                                              {
                                                  if (options.Headers.ContainsKey(header.Key))
                                                  {
                                                      options.Headers[header.Key] = header.Value;
                                                  }
                                                  else
                                                  {
                                                      options.Headers.Add(header.Key, header.Value);
                                                  }
                                              }
                                          };
                                      }
                                      
                                      private static Uri AddParametersToUri(
                                      Dictionary<string, string>? parameters, Uri uri)
                                      {
                                          if (parameters == null || parameters.Count == 0)
                                          {
                                              return uri;
                                          }
                                      
                                          var uriBuilder = new UriBuilder(uri);
                                          var query = System.Web.HttpUtility.ParseQueryString(uriBuilder.Query);
                                      
                                          foreach (var parameter in parameters)
                                          {
                                              query[parameter.Key] = parameter.Value;
                                          }
                                      
                                          uriBuilder.Query = query.ToString();
                                          return uriBuilder.Uri;
                                      }
                                      
                                      private static IEnumerable<TimeSpan> DefaultRetrySteps
                                      {
                                          get
                                          {
                                              var retrySteps = Enumerable.Repeat(TimeSpan.FromSeconds(1), 10);
                                              retrySteps =
                                                  retrySteps.Concat(Enumerable.Repeat(TimeSpan.FromSeconds(3),
                                                      5));
                                              retrySteps =
                                                  retrySteps.Concat(
                                                      Enumerable.Repeat(TimeSpan.FromSeconds(10), 2));
                                              return retrySteps;
                                          }
                                      }
                                  }
                                  """;
    
    internal static SourceText GetSource(MsBuildOptions? options)
    {
        var template = HubClientBaseTemplate.Replace("{~{namespaceName}~}", options?.RootNamespace ?? "SignalRGen.Generator");

        return SourceText.From(template, Encoding.UTF8);
    }
}