using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SignalRGen.Generator.Common;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class HubClientSource
{
    internal static SourceText GetSourceText(HubClientToGenerate hubClientToGenerate)
    {
        var template =
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            
            {~{usings}~}
            
            #nullable enable
            
            namespace {~{namespaceName}~};
            
            /// <summary>
            /// Represents a HubClient for the <see cref = "{~{hubClientInterface}~}"/> interface.
            /// </summary>
            public class {~{hubName}~} : HubClientBase, IHubClient
            {
                public static string HubUri { get; } = "{~{hubUri}~}";
                public {~{hubName}~}(IHubConnectionBuilder hubConnectionBuilder) : base(hubConnectionBuilder)
                {
                }
                
            {~{methods}~}
                
                protected override void RegisterHubMethods()
                {
                {~{onMethods}~}
                }
            }
            """;
        var methodTemplate =
            """
                /// <summary>
                /// Is invoked whenever the client method {~{identifier}~} of the <see cref = "{~{hubClientInterface}~}"/> gets invoked.
                /// </summary>
                public Func<{~{parameterTypes}~}, Task>? On{~{identifier}~} = default;
                private Task {~{identifier}~}Handler({~{parameterList}~})
                {
                    return On{~{identifier}~}?.Invoke({~{parameters}~}) ?? Task.CompletedTask;
                }
            """;
        var onMethodTemplate =
            """
                _hubConnection?.On<{~{parameterTypes}~}>("{~{identifier}~}", {~{identifier}~}Handler);
            """;

        var allUsings =
            hubClientToGenerate.Usings.Append(new CacheableUsingDeclaration("using Microsoft.AspNetCore.SignalR.Client;"));
        var usings = string.Join("\n", allUsings.Select(u => u.UsingNamespace));

        var methods = hubClientToGenerate.Methods.Select(method =>
            {
                var parameterTypes = string.Join(", ", method.Parameters.Select(p => p.Type));
                var parameterList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                var parameters = string.Join(", ", method.Parameters.Select(p => p.Name));

                return methodTemplate
                    .Replace("{~{hubClientInterface}~}", hubClientToGenerate.InterfaceName)
                    .Replace("{~{identifier}~}", method.Identifier)
                    .Replace("{~{parameterTypes}~}", parameterTypes)
                    .Replace("{~{parameterList}~}", parameterList)
                    .Replace("{~{parameters}~}", parameters);
            })
            .ToArray();

        var onMethods = hubClientToGenerate.Methods
            .Select(method =>
            {
                var parameterTypes = string.Join(", ", method.Parameters.Select(p => p.Type));

                return onMethodTemplate.Replace("{~{identifier}~}", method.Identifier)
                    .Replace("{~{parameterTypes}~}", parameterTypes);
            })
            .ToArray();

        template = template
            .Replace("{~{usings}~}", usings)
            .Replace("{~{namespaceName}~}", "SignalRGen.Generator")
            .Replace("{~{hubName}~}", hubClientToGenerate.HubName)
            .Replace("{~{hubUri}~}", hubClientToGenerate.HubUri)
            .Replace("{~{hubClientInterface}~}", hubClientToGenerate.InterfaceName)
            .Replace("{~{methods}~}", string.Join("\n", methods))
            .Replace("{~{onMethods}~}", string.Join("\n\t", onMethods));


        return SourceText.From(template, Encoding.UTF8);
    }

    // internal static SourceText GetSourceText(
    //     HubClientToGenerate hubClientToGenerate)
    // {
    //     var memberList =
    //         new List<MemberDeclarationSyntax>()
    //         {
    //             CreateHubUri(hubClientToGenerate),
    //             CreateCtor(hubClientToGenerate)
    //         };
    //     foreach (var clientMethod in hubClientToGenerate.Methods)
    //     {
    //         memberList.Add(CreateEventHandler(hubClientToGenerate.InterfaceName, clientMethod));
    //         memberList.Add(CreateClientHandlerMethod(clientMethod));
    //     }
    //
    //     memberList.Add(CreateRegisterHubMethods(hubClientToGenerate));
    //
    //     var usings = new List<UsingDirectiveSyntax>()
    //     {
    //         UsingDirective(
    //                 QualifiedName(
    //                     QualifiedName(
    //                         QualifiedName(
    //                             IdentifierName("Microsoft"),
    //                             IdentifierName("AspNetCore")),
    //                         IdentifierName("SignalR")),
    //                     IdentifierName("Client")))
    //             .WithUsingKeyword(
    //                 AutoGeneratedHintSource.GetSyntaxToken(SyntaxKind
    //                     .UsingKeyword))
    //     };
    //     usings.AddRange(hubClientToGenerate.Usings);
    //
    //     return CompilationUnit()
    //         .WithUsings(
    //             List<UsingDirectiveSyntax>(usings))
    //         .WithMembers(
    //             SingletonList<MemberDeclarationSyntax>(
    //                 FileScopedNamespaceDeclaration(
    //                         QualifiedName(
    //                             IdentifierName("SignalRGen"),
    //                             IdentifierName("Generator")))
    //                     .WithNamespaceKeyword(
    //                         NullableEnabledSource.GetSyntaxToken(SyntaxKind
    //                             .NamespaceKeyword))
    //                     .WithMembers(
    //                         SingletonList<MemberDeclarationSyntax>(
    //                             ClassDeclaration(hubClientToGenerate.HubName)
    //                                 .WithModifiers(
    //                 TokenList(
    //                     Token(
    //                         TriviaList(
    //                             Trivia(
    //                                 DocumentationCommentTrivia(
    //                                     SyntaxKind.SingleLineDocumentationCommentTrivia,
    //                                     List<XmlNodeSyntax>(
    //                                         new XmlNodeSyntax[]{
    //                                             XmlText()
    //                                             .WithTextTokens(
    //                                                 TokenList(
    //                                                     XmlTextLiteral(
    //                                                         TriviaList(
    //                                                             DocumentationCommentExterior("///")),
    //                                                         " ",
    //                                                         " ",
    //                                                         TriviaList()))),
    //                                             XmlExampleElement(
    //                                                 XmlText()
    //                                                 .WithTextTokens(
    //                                                     TokenList(
    //                                                         new []{
    //                                                             XmlTextNewLine(
    //                                                                 TriviaList(),
    //                                                                 "\n",
    //                                                                 "\n",
    //                                                                 TriviaList()),
    //                                                             XmlTextLiteral(
    //                                                                 TriviaList(
    //                                                                     DocumentationCommentExterior("///")),
    //                                                                 " Represents a HubClient for the ",
    //                                                                 " Represents a HubClient for the ",
    //                                                                 TriviaList())})),
    //                                                 XmlNullKeywordElement()
    //                                                 .WithAttributes(
    //                                                     SingletonList<XmlAttributeSyntax>(
    //                                                         XmlCrefAttribute(
    //                                                             NameMemberCref(
    //                                                                 IdentifierName(hubClientToGenerate.InterfaceName))))),
    //                                                 XmlText()
    //                                                 .WithTextTokens(
    //                                                     TokenList(
    //                                                         new []{
    //                                                             XmlTextLiteral(
    //                                                                 TriviaList(),
    //                                                                 " interface.",
    //                                                                 " interface.",
    //                                                                 TriviaList()),
    //                                                             XmlTextNewLine(
    //                                                                 TriviaList(),
    //                                                                 "\n",
    //                                                                 "\n",
    //                                                                 TriviaList()),
    //                                                             XmlTextLiteral(
    //                                                                 TriviaList(
    //                                                                     DocumentationCommentExterior("///")),
    //                                                                 " ",
    //                                                                 " ",
    //                                                                 TriviaList())})))
    //                                             .WithStartTag(
    //                                                 XmlElementStartTag(
    //                                                     XmlName(
    //                                                         Identifier("summary"))))
    //                                             .WithEndTag(
    //                                                 XmlElementEndTag(
    //                                                     XmlName(
    //                                                         Identifier("summary")))),
    //                                             XmlText()
    //                                             .WithTextTokens(
    //                                                 TokenList(
    //                                                     XmlTextNewLine(
    //                                                         TriviaList(),
    //                                                         "\n",
    //                                                         "\n",
    //                                                         TriviaList())))})))),
    //                         SyntaxKind.PublicKeyword,
    //                         TriviaList())))
    //                                 .WithBaseList(
    //                                     BaseList(
    //                                         SeparatedList<BaseTypeSyntax>(
    //                                             new SyntaxNodeOrToken[]
    //                                             {
    //                                                 SimpleBaseType(
    //                                                     IdentifierName(
    //                                                         "HubClientBase")),
    //                                                 Token(SyntaxKind
    //                                                     .CommaToken),
    //                                                 SimpleBaseType(
    //                                                     IdentifierName(
    //                                                         "IHubClient"))
    //                                             })))
    //                                 .WithMembers(
    //                                     List<MemberDeclarationSyntax>(
    //                                         memberList))))))
    //         .NormalizeWhitespace().GetText(Encoding.UTF8);
    // }
    //
    // private static PropertyDeclarationSyntax CreateHubUri(
    //     HubClientToGenerate hubClientToGenerate)
    // {
    //     return PropertyDeclaration(
    //             PredefinedType(
    //                 Token(SyntaxKind.StringKeyword)),
    //             Identifier("HubUri"))
    //         .WithModifiers(
    //             TokenList(
    //                 new[]
    //                 {
    //                     Token(SyntaxKind.PublicKeyword),
    //                     Token(SyntaxKind.StaticKeyword)
    //                 }))
    //         .WithAccessorList(
    //             AccessorList(
    //                 SingletonList<AccessorDeclarationSyntax>(
    //                     AccessorDeclaration(
    //                             SyntaxKind.GetAccessorDeclaration)
    //                         .WithSemicolonToken(
    //                             Token(SyntaxKind.SemicolonToken)))))
    //         .WithInitializer(
    //             EqualsValueClause(
    //                 LiteralExpression(
    //                     SyntaxKind.StringLiteralExpression,
    //                     Literal(hubClientToGenerate.HubUri))))
    //         .WithSemicolonToken(
    //             Token(SyntaxKind.SemicolonToken));
    // }
    //
    // private static FieldDeclarationSyntax CreateEventHandler(string interfaceName,
    //     MethodDeclarationSyntax clientMethod)
    // {
    //     var parameterTypes =
    //         clientMethod.ParameterList.Parameters.Select(p =>
    //             p.Type.ToString());
    //     var funcGenerics = new SyntaxNodeOrTokenList();
    //     foreach (var parameterType in parameterTypes)
    //     {
    //         funcGenerics = funcGenerics.Add(IdentifierName(parameterType));
    //         funcGenerics = funcGenerics.Add(Token(SyntaxKind.CommaToken));
    //     }
    //
    //     funcGenerics = funcGenerics.Add(IdentifierName("Task"));
    //
    //     return FieldDeclaration(
    //             VariableDeclaration(
    //                     NullableType(
    //                         GenericName(
    //                                 Identifier("Func"))
    //                             .WithTypeArgumentList(
    //                                 TypeArgumentList(
    //                                     SeparatedList<TypeSyntax>(
    //                                         funcGenerics)))))
    //                 .WithVariables(
    //                     SingletonSeparatedList<
    //                         VariableDeclaratorSyntax>(
    //                         VariableDeclarator(
    //                                 Identifier(
    //                                     $"On{clientMethod.Identifier.ToString()}"))
    //                             .WithInitializer(
    //                                 EqualsValueClause(
    //                                     LiteralExpression(
    //                                         SyntaxKind
    //                                             .DefaultLiteralExpression,
    //                                         Token(SyntaxKind
    //                                             .DefaultKeyword)))))))
    //         .WithModifiers(
    //                 TokenList(
    //                     Token(
    //                         TriviaList(
    //                             Trivia(
    //                                 DocumentationCommentTrivia(
    //                                     SyntaxKind.SingleLineDocumentationCommentTrivia,
    //                                     List<XmlNodeSyntax>(
    //                                         new XmlNodeSyntax[]{
    //                                             XmlText()
    //                                             .WithTextTokens(
    //                                                 TokenList(
    //                                                     XmlTextLiteral(
    //                                                         TriviaList(
    //                                                             DocumentationCommentExterior("///")),
    //                                                         " ",
    //                                                         " ",
    //                                                         TriviaList()))),
    //                                             XmlExampleElement(
    //                                                 XmlText()
    //                                                 .WithTextTokens(
    //                                                     TokenList(
    //                                                         new []{
    //                                                             XmlTextNewLine(
    //                                                                 TriviaList(),
    //                                                                 "\n",
    //                                                                 "\n",
    //                                                                 TriviaList()),
    //                                                             XmlTextLiteral(
    //                                                                 TriviaList(
    //                                                                     DocumentationCommentExterior("    ///")),
    //                                                                 $" Is invoked whenever the client method {clientMethod.Identifier.ToString()} of the ",
    //                                                                 $" Is invoked whenever the client method {clientMethod.Identifier.ToString()} of the ",
    //                                                                 TriviaList())})),
    //                                                 XmlNullKeywordElement()
    //                                                 .WithAttributes(
    //                                                     SingletonList<XmlAttributeSyntax>(
    //                                                         XmlCrefAttribute(
    //                                                             NameMemberCref(
    //                                                                 IdentifierName(interfaceName))))),
    //                                                 XmlText()
    //                                                 .WithTextTokens(
    //                                                     TokenList(
    //                                                         new []{
    //                                                             XmlTextLiteral(
    //                                                                 TriviaList(),
    //                                                                 " gets invoked.",
    //                                                                 " gets invoked.",
    //                                                                 TriviaList()),
    //                                                             XmlTextNewLine(
    //                                                                 TriviaList(),
    //                                                                 "\n",
    //                                                                 "\n",
    //                                                                 TriviaList()),
    //                                                             XmlTextLiteral(
    //                                                                 TriviaList(
    //                                                                     DocumentationCommentExterior("    ///")),
    //                                                                 " ",
    //                                                                 " ",
    //                                                                 TriviaList())})))
    //                                             .WithStartTag(
    //                                                 XmlElementStartTag(
    //                                                     XmlName(
    //                                                         Identifier("summary"))))
    //                                             .WithEndTag(
    //                                                 XmlElementEndTag(
    //                                                     XmlName(
    //                                                         Identifier("summary")))),
    //                                             XmlText()
    //                                             .WithTextTokens(
    //                                                 TokenList(
    //                                                     XmlTextNewLine(
    //                                                         TriviaList(),
    //                                                         "\n",
    //                                                         "\n",
    //                                                         TriviaList())))})))),
    //                         SyntaxKind.PublicKeyword,
    //                         TriviaList())));
    // }
    //
    // private static MethodDeclarationSyntax CreateClientHandlerMethod(
    //     MethodDeclarationSyntax clientMethod)
    // {
    //     var onHandleMethod =
    //         IdentifierName($"On{clientMethod.Identifier.ToString()}");
    //     var handlerInvokation = InvocationExpression(
    //         MemberBindingExpression(
    //             IdentifierName(
    //                 "Invoke")));
    //
    //     var eventHandlerArguments =
    //         clientMethod.ParameterList.Parameters.Select(p => p.Identifier)
    //             .ToList();
    //
    //     var argumentList = new SyntaxNodeOrTokenList();
    //     if (eventHandlerArguments.Any())
    //     {
    //         argumentList = argumentList.Add(
    //             Argument(IdentifierName(eventHandlerArguments.First())));
    //         foreach (var argument in eventHandlerArguments.Skip(1))
    //         {
    //             argumentList = argumentList.Add(Token(SyntaxKind.CommaToken));
    //             argumentList = argumentList.Add(Argument(IdentifierName(argument)));
    //         }
    //
    //         if (argumentList.Count > 1)
    //         {
    //             handlerInvokation = handlerInvokation.WithArgumentList(
    //                 ArgumentList(
    //                     SeparatedList<ArgumentSyntax>(argumentList)));
    //         }
    //         else
    //         {
    //             handlerInvokation = handlerInvokation.WithArgumentList(
    //                 ArgumentList(SingletonSeparatedList<ArgumentSyntax>(
    //                     Argument(
    //                         IdentifierName(eventHandlerArguments
    //                             .First())))));
    //         }
    //     }
    //
    //     return MethodDeclaration(
    //             IdentifierName(
    //                 "Task"),
    //             Identifier($"{clientMethod.Identifier.ToString()}Handler"))
    //         .WithModifiers(
    //             TokenList(
    //                 Token(SyntaxKind
    //                     .PrivateKeyword)))
    //         .WithParameterList(clientMethod.ParameterList)
    //         .WithBody(
    //             Block(
    //                 SingletonList<
    //                     StatementSyntax>(
    //                     ReturnStatement(
    //                         BinaryExpression(SyntaxKind.CoalesceExpression,
    //                             ConditionalAccessExpression(onHandleMethod,
    //                                 handlerInvokation),
    //                             MemberAccessExpression(
    //                                 SyntaxKind.SimpleMemberAccessExpression,
    //                                 IdentifierName("Task"),
    //                                 IdentifierName("CompletedTask")))))));
    // }
    //
    // private static ConstructorDeclarationSyntax CreateCtor(
    //     HubClientToGenerate hubClient)
    // {
    //     return ConstructorDeclaration(
    //             Identifier(
    //                 hubClient.HubName))
    //         .WithModifiers(
    //             TokenList(
    //                 Token(SyntaxKind
    //                     .PublicKeyword)))
    //         .WithParameterList(
    //             ParameterList(
    //                 SingletonSeparatedList
    //                     <ParameterSyntax>(
    //                         Parameter(
    //                                 Identifier(
    //                                     "hubConnectionBuilder"))
    //                             .WithType(
    //                                 IdentifierName(
    //                                     "IHubConnectionBuilder")))))
    //         .WithInitializer(
    //             ConstructorInitializer(
    //                 SyntaxKind
    //                     .BaseConstructorInitializer,
    //                 ArgumentList(
    //                     SingletonSeparatedList
    //                         <ArgumentSyntax>(
    //                             Argument(
    //                                 IdentifierName(
    //                                     "hubConnectionBuilder"))))))
    //         .WithBody(
    //             Block());
    // }
    //
    // private static MethodDeclarationSyntax CreateRegisterHubMethods(
    //     HubClientToGenerate hubClientToGenerate)
    // {
    //     var methodRegistration = new SyntaxList<ExpressionStatementSyntax>();
    //     foreach (var clientMethod in hubClientToGenerate.Methods)
    //     {
    //         var method = CreateOnMethod(clientMethod);
    //         methodRegistration = methodRegistration.Add(method);
    //     }
    //
    //     return MethodDeclaration(
    //             PredefinedType(
    //                 Token(SyntaxKind
    //                     .VoidKeyword)),
    //             Identifier(
    //                 "RegisterHubMethods"))
    //         .WithModifiers(
    //             TokenList(
    //                 new[]
    //                 {
    //                     Token(
    //                         SyntaxKind
    //                             .ProtectedKeyword),
    //                     Token(
    //                         SyntaxKind
    //                             .OverrideKeyword)
    //                 }))
    //         .WithBody(
    //             Block(methodRegistration));
    // }
    //
    // private static ExpressionStatementSyntax CreateOnMethod(
    //     CacheableMethodDeclaration clientMethod)
    // {
    //     TypeArgumentListSyntax onGenericList;
    //     var parameterTypes = clientMethod.Parameters;
    //     if (parameterTypes.Count() > 1)
    //     {
    //         var argumentList = new SyntaxNodeOrTokenList();
    //         argumentList = argumentList.Add(parameterTypes.First());
    //         foreach (var type in parameterTypes.Skip(1))
    //         {
    //             argumentList = argumentList.Add(Token(SyntaxKind.CommaToken));
    //             argumentList = argumentList.Add(type);
    //         }
    //
    //         onGenericList =
    //             TypeArgumentList(SeparatedList<TypeSyntax>(argumentList));
    //     }
    //     else
    //     {
    //         onGenericList = TypeArgumentList(
    //             SingletonSeparatedList<TypeSyntax>(parameterTypes.First()));
    //     }
    //
    //     return ExpressionStatement(
    //         InvocationExpression(
    //                 MemberAccessExpression(
    //                     SyntaxKind
    //                         .SimpleMemberAccessExpression,
    //                     IdentifierName(
    //                         "_hubConnection"),
    //                     GenericName(
    //                             Identifier(
    //                                 "On"))
    //                         .WithTypeArgumentList(onGenericList)))
    //             .WithArgumentList(
    //                 ArgumentList(
    //                     SeparatedList
    //                         <ArgumentSyntax>(
    //                             new
    //                                 SyntaxNodeOrToken
    //                                 []
    //                                 {
    //                                     Argument(
    //                                         LiteralExpression(
    //                                             SyntaxKind
    //                                                 .StringLiteralExpression,
    //                                             Literal(
    //                                                 clientMethod.Identifier
    //                                                     .ToString()))),
    //                                     Token(
    //                                         SyntaxKind
    //                                             .CommaToken),
    //                                     Argument(
    //                                         IdentifierName(
    //                                             $"{clientMethod.Identifier.ToString()}Handler"))
    //                                 }))));
    // }
}