using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class HubClientAttributeSource
{
    internal static SourceText GetSource()
    {
        var template =
            $$"""
            {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}
            
            using System;
            
            #nullable enable
            namespace SignalRGen.Generator;
            
            /// <summary>
            /// Marker Attribute for a HubClient.
            /// </summary>
            [AttributeUsage(AttributeTargets.Interface)]
            public sealed class HubClientAttribute : Attribute
            {
                public string? HubName { get; init; }
                public required string HubUri { get; init; }
            }
            """;
        
        return SourceText.From(template, Encoding.UTF8);
    }
}