using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class HubClientBaseSource
{
    internal static SourceText GetSource()
    {
        const string template = $$"""
                                  {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}

                                  using Microsoft.AspNetCore.SignalR.Client;

                                  #nullable enable
                                  namespace SignalRGen.Generator;

                                  /// <summary>
                                  /// Base class for generated HubClients.
                                  /// </summary>
                                  /// <remarks>
                                  /// This base is partial to allow for extensions for all clients.
                                  /// Be aware that any extended behavior might result in the need to rewrite the DisposeAsync.
                                  /// </remarks>
                                  public abstract partial class HubClientBase : IAsyncDisposable
                                  {
                                      protected bool _isRegistered;
                                      protected HubConnection? _hubConnection;
                                      protected readonly IHubConnectionBuilder HubConnectionBuilder;
                                      
                                      /// <summary>
                                      /// Gets invoked each time the Closed event from the underlying <see cref = "HubConnection"/> occurs.
                                      /// </summary>
                                      public Func<Exception?, Task>? Closed;
                                      
                                      /// <summary>
                                      /// Gets invoked each time the Reconnecting event from the underlying <see cref = "HubConnection"/> occurs.
                                      /// </summary>
                                      public Func<Exception?, Task>? Reconnecting;
                                      
                                      /// <summary>
                                      /// Gets invoked each time the reconnected event from the underlying <see cref = "HubConnection"/> occurs.
                                      /// </summary>
                                      public Func<Task>? Reconnected;
                                      
                                      protected HubClientBase(IHubConnectionBuilder hubConnectionBuilder)
                                      {
                                          HubConnectionBuilder = hubConnectionBuilder;
                                      }

                                      /// <summary>
                                      /// Asynchronously starts the underlying <see cref = "HubConnection"/> and registers the event callbacks for the SignalR client methods.
                                      /// </summary>
                                      /// <param name = "cancellationToken">A <see cref = "CancellationToken"/> to cancel the start of the <see cref = "HubConnection"/>.</param>
                                      public virtual Task StartAsync(CancellationToken cancellationToken = default)
                                      {
                                          _hubConnection ??= HubConnectionBuilder.Build();
                                          if (!_isRegistered)
                                          {
                                              _hubConnection.Closed += Closed;
                                              _hubConnection.Reconnected += OnReconnected;
                                              _hubConnection.Reconnecting += Reconnecting;
                                              RegisterHubMethods();
                                              _isRegistered = true;
                                          }

                                          return _hubConnection.State == HubConnectionState.Disconnected ? _hubConnection.StartAsync(cancellationToken) : Task.CompletedTask;
                                      }

                                      /// <summary>
                                      /// Asynchronously stops the underlying <see cref = "HubConnection"/>.
                                      /// </summary>
                                      /// <param name = "cancellationToken">A <see cref = "CancellationToken"/> to cancel the stop of the <see cref = "HubConnection"/>.</param>
                                      public virtual Task StopAsync(CancellationToken cancellationToken = default)
                                      {
                                          return _hubConnection is null ? Task.CompletedTask : _hubConnection.StopAsync(cancellationToken);
                                      }

                                      protected abstract void RegisterHubMethods();
                                      private Task OnReconnected(string? connectionId)
                                      {
                                          return Reconnected is not null ? Reconnected.Invoke() : Task.CompletedTask;
                                      }

                                      /// <summary>
                                      /// Releases resources for the underlying <see cref = "HubConnection"/>.
                                      /// </summary>
                                      /// <returns>A <see cref = "ValueTask"/> that completes when resources have been released.</returns>
                                      public ValueTask DisposeAsync()
                                      {
                                          if (_hubConnection is null)
                                          {
                                              return ValueTask.CompletedTask;
                                          }

                                          _hubConnection.Closed -= Closed;
                                          _hubConnection.Reconnected -= OnReconnected;
                                          _hubConnection.Reconnecting -= Reconnecting;
                                          return _hubConnection.DisposeAsync();
                                      }
                                  }
                                  """;

        return SourceText.From(template, Encoding.UTF8);
    }
}