using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class IHubClientSource
{
    internal static SourceText GetSource()
    {
        const string template = $$"""
                                  {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}

                                  #nullable enable
                                  namespace SignalRGen.Generator;

                                  public interface IHubClient
                                  {
                                      static abstract string HubUri { get; }
                                  }
                                  """;

        return SourceText.From(template, Encoding.UTF8);
    }
}