using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class IHubClientSource
{
    internal static SourceText GetSource() => CompilationUnit()
        .WithMembers(
            SingletonList<MemberDeclarationSyntax>(
                FileScopedNamespaceDeclaration(
                        QualifiedName(
                            IdentifierName("SignalRGen"),
                            IdentifierName("Generator")))
                    .WithNamespaceKeyword(
                        Token(
                            TriviaList(new[] { NullableEnabledSource.NullableEnabledTrivia() })
                                .InsertRange(0, AutoGeneratedHintSource.AutoGeneratedHint()),
                            SyntaxKind.NamespaceKeyword,
                            TriviaList()))
                    .WithMembers(
                        SingletonList<MemberDeclarationSyntax>(
                            InterfaceDeclaration("IHubClient")
                                .WithModifiers(
                                    TokenList(
                                        Token(SyntaxKind.PublicKeyword)))
                                .WithMembers(
                                    SingletonList<MemberDeclarationSyntax>(
                                        PropertyDeclaration(
                                                PredefinedType(
                                                    Token(SyntaxKind
                                                        .StringKeyword)),
                                                Identifier("HubUri"))
                                            .WithModifiers(
                                                TokenList(
                                                    new[]
                                                    {
                                                        Token(SyntaxKind
                                                            .StaticKeyword),
                                                        Token(SyntaxKind
                                                            .AbstractKeyword)
                                                    }))
                                            .WithAccessorList(
                                                AccessorList(
                                                    SingletonList<
                                                        AccessorDeclarationSyntax>(
                                                        AccessorDeclaration(
                                                                SyntaxKind
                                                                    .GetAccessorDeclaration)
                                                            .WithSemicolonToken(
                                                                Token(SyntaxKind
                                                                    .SemicolonToken)))))))))))
        .NormalizeWhitespace()
        .GetText(Encoding.UTF8);
}