using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SignalRGen.Generator.Sources;

public static class SignalROptionsSource
{
    internal static SourceText GetSource()
    {
        const string template = $$"""
                                  {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}

                                  #nullable enable
                                  namespace SignalRGen.Generator.Client.Configuration;

                                  /// <summary>
                                  /// Encapsulates the options to configure a SignalR Client.
                                  /// </summary>
                                  public class SignalROptions
                                  {
                                      /// <summary>The base <see cref="Uri"/> for the SignalR Client.</summary>
                                      /// <remarks>This <see cref="Uri"/> will be used for every `With...` Hub defined.</remarks>
                                      public Uri HubBaseUri { get; set; } = default!;
                                  }
                                  """;

        return SourceText.From(template, Encoding.UTF8);
    }
}
