using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

public static class SignalROptionsSource
{
    public static SourceText GetSource() => CompilationUnit()
        .WithMembers(
            SingletonList<MemberDeclarationSyntax>(
                FileScopedNamespaceDeclaration(
                        QualifiedName(
                            QualifiedName(
                                QualifiedName(
                                    IdentifierName("SignalRGen"),
                                    IdentifierName("Generator")),
                                IdentifierName("Client")),
                            IdentifierName("Configuration")))
                    .WithNamespaceKeyword(
                        Token(
                            TriviaList(new[] { NullableEnabledSource.NullableEnabledTrivia() })
                                .InsertRange(0, AutoGeneratedHintSource.AutoGeneratedHint()),
                            SyntaxKind.NamespaceKeyword,
                            TriviaList()))
                        .WithMembers(
                        SingletonList<MemberDeclarationSyntax>(
                            ClassDeclaration("SignalROptions")
                                .WithModifiers(
                                    TokenList(
                                        Token(SyntaxKind.PublicKeyword)))
                                .WithMembers(
                                    SingletonList<MemberDeclarationSyntax>(
                                        PropertyDeclaration(
                                                IdentifierName("Uri"),
                                                Identifier("HubBaseUri"))
                                            .WithModifiers(
                                                TokenList(
                                                    Token(SyntaxKind
                                                        .PublicKeyword)))
                                            .WithAccessorList(
                                                AccessorList(
                                                    List<
                                                        AccessorDeclarationSyntax>(
                                                        new
                                                            AccessorDeclarationSyntax
                                                            []
                                                            {
                                                                AccessorDeclaration(
                                                                        SyntaxKind
                                                                            .GetAccessorDeclaration)
                                                                    .WithSemicolonToken(
                                                                        Token(
                                                                            SyntaxKind
                                                                                .SemicolonToken)),
                                                                AccessorDeclaration(
                                                                        SyntaxKind
                                                                            .SetAccessorDeclaration)
                                                                    .WithSemicolonToken(
                                                                        Token(
                                                                            SyntaxKind
                                                                                .SemicolonToken))
                                                            })))
                                            .WithInitializer(
                                                EqualsValueClause(
                                                    PostfixUnaryExpression(
                                                        SyntaxKind
                                                            .SuppressNullableWarningExpression,
                                                        LiteralExpression(
                                                            SyntaxKind
                                                                .DefaultLiteralExpression,
                                                            Token(SyntaxKind
                                                                .DefaultKeyword)))))
                                            .WithSemicolonToken(
                                                Token(SyntaxKind
                                                    .SemicolonToken))))))))
        .NormalizeWhitespace().GetText(Encoding.UTF8);
}
