using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

public static class SignalROptionsSource
{
    internal static SourceText GetSource()
    {
        var template =
            $$"""
            {{AutoGeneratedHintSource.AutoGeneratedHintTemplate}}
            
            #nullable enable
            namespace SignalRGen.Generator.Client.Configuration;
            
            public class SignalROptions
            {
                public Uri HubBaseUri { get; set; } = default !;
            }
            """;
        
        return SourceText.From(template, Encoding.UTF8);
    }
}
