using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class FmSignalRHubServiceCollectionSource
{
    public static SourceText GetSource() => CompilationUnit()
        .WithUsings(
            List<UsingDirectiveSyntax>(
                new UsingDirectiveSyntax[]{
                    UsingDirective(
                        QualifiedName(
                            QualifiedName(
                                QualifiedName(
                                    IdentifierName("SignalRGen"),
                                    IdentifierName("Generator")),
                                IdentifierName("Client")),
                            IdentifierName("Configuration")))
                        .WithUsingKeyword(AutoGeneratedHintSource.GetSyntaxToken(SyntaxKind.UsingKeyword)),
                    UsingDirective(
                        QualifiedName(
                            QualifiedName(
                                QualifiedName(
                                    IdentifierName("Microsoft"),
                                    IdentifierName("AspNetCore")),
                                IdentifierName("SignalR")),
                            IdentifierName("Client")))
                        .WithUsingKeyword(AutoGeneratedHintSource.GetSyntaxToken(SyntaxKind.UsingKeyword)),
                    UsingDirective(
                        QualifiedName(
                            QualifiedName(
                                IdentifierName("Microsoft"),
                                IdentifierName("Extensions")),
                            IdentifierName("DependencyInjection")))}))
        .WithMembers(
            SingletonList<MemberDeclarationSyntax>(
                FileScopedNamespaceDeclaration(
                        QualifiedName(
                            QualifiedName(
                                QualifiedName(
                                    QualifiedName(
                                        IdentifierName("SignalRGen"),
                                        IdentifierName("Generator")),
                                    IdentifierName("Client")),
                                IdentifierName("Extensions")),
                            IdentifierName("DependencyInjection")))
                    .WithNamespaceKeyword(NullableEnabledSource.GetSyntaxToken(SyntaxKind.NamespaceKeyword))
                    .WithMembers(
                        SingletonList<MemberDeclarationSyntax>(
                            RecordDeclaration(
                                    Token(SyntaxKind.RecordKeyword),
                                    Identifier("SignalRHubServiceCollection"))
                                .WithModifiers(
                                    TokenList(
                                        Token(SyntaxKind.PublicKeyword)))
                                .WithParameterList(
                                    ParameterList(
                                        SeparatedList<ParameterSyntax>(
                                            new SyntaxNodeOrToken[]
                                            {
                                                Parameter(
                                                        Identifier("Services"))
                                                    .WithType(
                                                        IdentifierName(
                                                            "IServiceCollection")),
                                                Token(SyntaxKind.CommaToken),
                                                Parameter(
                                                        Identifier(
                                                            "GeneralConfiguration"))
                                                    .WithType(
                                                        IdentifierName(
                                                            "SignalROptions"))
                                            })))
                                .WithSemicolonToken(
                                    Token(SyntaxKind.SemicolonToken))))))
        .NormalizeWhitespace()
        .GetText(Encoding.UTF8);
}
