using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SignalRGen.Generator.Sources;

internal static class FmSignalRHubServiceCollectionSource
{
    internal static SourceText GetSource()
    {
        const string template = $"""
                                  {AutoGeneratedHintSource.AutoGeneratedHintTemplate}

                                  using SignalRGen.Generator.Client.Configuration;
                                  using Microsoft.AspNetCore.SignalR.Client;
                                  using Microsoft.Extensions.DependencyInjection;

                                  #nullable enable
                                  namespace SignalRGen.Generator.Client.Extensions.DependencyInjection;

                                  public record SignalRHubServiceCollection(IServiceCollection Services, SignalROptions GeneralConfiguration);
                                  """;

        return SourceText.From(template, Encoding.UTF8);
    }
}
