using SignalRGen.Generator.Tests;

namespace SignalRGen.Testing.Generator.Tests;

public class FakeHubClientTests
{
    [Fact]
    public Task Generates_FakeHubClient_Correctly()
    {
        // Arrange
        const string source = """
                              [assembly: SignalRGen.Testing.Abstractions.Attributes.GenerateFakeForHubClient(typeof(SignalRGen.Clients.TestHubClient))]
                              
                              //HintName: TestHubClient.g.cs
                              //------------------------------------------------------------------------------
                              // <auto-generated>
                              //     This code was generated by a tool.
                              //
                              //     Changes to this file may cause incorrect behavior and will be lost if
                              //     the code is regenerated.
                              // </auto-generated>
                              //------------------------------------------------------------------------------
                              
                              #nullable enable
                              
                              namespace SignalRGen.Clients;
                              
                              /// <summary>
                              /// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.ITestHub"/> interface.
                              /// </summary>
                              public class TestHubClient : HubClientBase
                              {
                                  public static string HubUri { get; } = "examples";
                                  public TestHubClient(
                                      global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
                                      global::System.Uri baseHubUri,
                                      global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
                                      : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
                                  {
                                  }
                                  
                                  /// <summary>
                                  /// Is invoked whenever the client method ReceiveCustomTypeUpdate of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>, global::System.Threading.Tasks.Task>? OnReceiveCustomTypeUpdate = default;
                                  private global::System.Threading.Tasks.Task ReceiveCustomTypeUpdateHandler(IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> customTypes)
                                  {
                                      return OnReceiveCustomTypeUpdate?.Invoke(customTypes) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                                  /// <summary>
                                  /// Is invoked whenever the client method ReceiveFooUpdate of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<string, int, global::System.Threading.Tasks.Task>? OnReceiveFooUpdate = default;
                                  private global::System.Threading.Tasks.Task ReceiveFooUpdateHandler(string bar, int bass)
                                  {
                                      return OnReceiveFooUpdate?.Invoke(bar, bass) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                                  /// <summary>
                                  /// Is invoked whenever the client method ReceiveNormalTypeWithSpecificAttributeApplied of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<string, int, global::System.Threading.Tasks.Task>? OnReceiveNormalTypeWithSpecificAttributeApplied = default;
                                  private global::System.Threading.Tasks.Task ReceiveNormalTypeWithSpecificAttributeAppliedHandler(string bazz, int buzz)
                                  {
                                      return OnReceiveNormalTypeWithSpecificAttributeApplied?.Invoke(bazz, buzz) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                                  /// <summary>
                                  /// Is invoked whenever the client method ReceiveWithArbitraryAttribute of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<int, global::System.Threading.Tasks.Task>? OnReceiveWithArbitraryAttribute = default;
                                  private global::System.Threading.Tasks.Task ReceiveWithArbitraryAttributeHandler(int blub)
                                  {
                                      return OnReceiveWithArbitraryAttribute?.Invoke(blub) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                              
                                  /// <summary>
                                  /// Can be invoked to trigger the SendClientToServerNoReturnType on the <see cref = "ITestHub"/>.
                                  /// </summary>
                                  /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
                                  public global::System.Threading.Tasks.Task InvokeSendClientToServerNoReturnTypeAsync(string rick, int age, global::System.Threading.CancellationToken ct = default)
                                  {
                                      ValidateHubConnection();
                                      return InvokeCoreAsync("SendClientToServerNoReturnType", new object?[] { rick, age }, cancellationToken: ct);
                                  }
                                  /// <summary>
                                  /// Can be invoked to trigger the SendClientToServerWithReturnType on the <see cref = "ITestHub"/>.
                                  /// </summary>
                                  /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
                                  public global::System.Threading.Tasks.Task<string> InvokeSendClientToServerWithReturnTypeAsync(string morty, bool partOfMission, global::System.Threading.CancellationToken ct = default)
                                  {
                                      ValidateHubConnection();
                                      return InvokeCoreAsync<string>("SendClientToServerWithReturnType", new object?[] { morty, partOfMission }, cancellationToken: ct);
                                  }
                                  
                                  protected override void RegisterHubMethods()
                                  {
                                      if (_hubConnection is null)
                                      {
                                          return;
                                      }
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>>(_hubConnection, "ReceiveCustomTypeUpdate", ReceiveCustomTypeUpdateHandler);
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "ReceiveFooUpdate", ReceiveFooUpdateHandler);
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "ReceiveNormalTypeWithSpecificAttributeApplied", ReceiveNormalTypeWithSpecificAttributeAppliedHandler);
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<int>(_hubConnection, "ReceiveWithArbitraryAttribute", ReceiveWithArbitraryAttributeHandler);
                                  }
                                  
                                  private void ValidateHubConnection()
                                  {
                                      if (_hubConnection is null)
                                      {
                                          throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
                                      }
                                  }
                              }
                              """;


        return TestHelper.Verify(source);
    }

    [Fact]
    public Task Generates_FakeHubClient_WithNoMethods_Correctly()
    {
        const string source = """
                              [assembly: SignalRGen.Testing.Abstractions.Attributes.GenerateFakeForHubClient(typeof(SignalRGen.Clients.EmptyHubClient))]
                              
                              //------------------------------------------------------------------------------
                              // <auto-generated>
                              //     This code was generated by a tool.
                              //
                              //     Changes to this file may cause incorrect behavior and will be lost if
                              //     the code is regenerated.
                              // </auto-generated>
                              //------------------------------------------------------------------------------

                              #nullable enable

                              namespace SignalRGen.Clients.Contracts;

                              /// <summary>
                              /// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.Contracts.IEmptyHub"/> interface.
                              /// </summary>
                              public class EmptyHubClient : HubClientBase
                              {
                                  public static string HubUri { get; } = "empty";
                                  public EmptyHubClient(
                                      global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
                                      global::System.Uri baseHubUri,
                                      global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
                                      : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
                                  {
                                  }
                                  

                                  
                                  protected override void RegisterHubMethods()
                                  {
                                      if (_hubConnection is null)
                                      {
                                          return;
                                      }
                                  }
                                  
                                  private void ValidateHubConnection()
                                  {
                                      if (_hubConnection is null)
                                      {
                                          throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
                                      }
                                  }
                              }
                              """;
        
        return TestHelper.Verify(source);
    }

    [Fact]
    public Task Generates_FakeHubClient_WithComplexHubClient_Correctly()
    {
        const string source = """
                              [assembly: SignalRGen.Testing.Abstractions.Attributes.GenerateFakeForHubClient(typeof(SignalRGen.Clients.BasicHubClient))]
                              
                              //------------------------------------------------------------------------------
                              // <auto-generated>
                              //     This code was generated by a tool.
                              //
                              //     Changes to this file may cause incorrect behavior and will be lost if
                              //     the code is regenerated.
                              // </auto-generated>
                              //------------------------------------------------------------------------------
                              
                              #nullable enable
                              
                              namespace SignalRGen.Clients;
                              
                              /// <summary>
                              /// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.IBasicHub"/> interface.
                              /// </summary>
                              public class BasicHubClient : HubClientBase
                              {
                                  public static string HubUri { get; } = "basic";
                                  public BasicHubClient(
                                      global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
                                      global::System.Uri baseHubUri,
                                      global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
                                      : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
                                  {
                                  }
                                  
                                  /// <summary>
                                  /// Is invoked whenever the client method SendFromServerToClientMessage of the <see cref = "global::SignalRGen.Clients.IBasicHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<global::SignalRGen.Clients.BasicMessage, global::System.Threading.Tasks.Task>? OnSendFromServerToClientMessage = default;
                                  private global::System.Threading.Tasks.Task SendFromServerToClientMessageHandler(global::SignalRGen.Clients.BasicMessage message)
                                  {
                                      return OnSendFromServerToClientMessage?.Invoke(message) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                                  /// <summary>
                                  /// Is invoked whenever the client method SendFromServerToClientWithList of the <see cref = "global::SignalRGen.Clients.IBasicHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage>, global::System.Threading.Tasks.Task>? OnSendFromServerToClientWithList = default;
                                  private global::System.Threading.Tasks.Task SendFromServerToClientWithListHandler(global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage> messages)
                                  {
                                      return OnSendFromServerToClientWithList?.Invoke(messages) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                                  /// <summary>
                                  /// Is invoked whenever the client method SendFromServerToClientPrimitiveTypes of the <see cref = "global::SignalRGen.Clients.IBasicHub"/> gets invoked.
                                  /// </summary>
                                  public global::System.Func<string, int, global::System.Threading.Tasks.Task>? OnSendFromServerToClientPrimitiveTypes = default;
                                  private global::System.Threading.Tasks.Task SendFromServerToClientPrimitiveTypesHandler(string foo, int bar)
                                  {
                                      return OnSendFromServerToClientPrimitiveTypes?.Invoke(foo, bar) ?? global::System.Threading.Tasks.Task.CompletedTask;
                                  }
                              
                                  /// <summary>
                                  /// Can be invoked to trigger the SendFromClientToServerMessage on the <see cref = "IBasicHub"/>.
                                  /// </summary>
                                  /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="BasicHubClient.StartAsync"/></exception>
                                  public global::System.Threading.Tasks.Task<global::SignalRGen.Clients.BasicReturn> InvokeSendFromClientToServerMessageAsync(string message, global::System.Threading.CancellationToken ct = default)
                                  {
                                      ValidateHubConnection();
                                      return InvokeCoreAsync<global::SignalRGen.Clients.BasicReturn>("SendFromClientToServerMessage", new object?[] { message }, cancellationToken: ct);
                                  }
                                  /// <summary>
                                  /// Can be invoked to trigger the SendFromClientToServerWithList on the <see cref = "IBasicHub"/>.
                                  /// </summary>
                                  /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="BasicHubClient.StartAsync"/></exception>
                                  public global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicReturn>> InvokeSendFromClientToServerWithListAsync(global::System.Collections.Generic.List<string> messages, global::System.Threading.CancellationToken ct = default)
                                  {
                                      ValidateHubConnection();
                                      return InvokeCoreAsync<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicReturn>>("SendFromClientToServerWithList", new object?[] { messages }, cancellationToken: ct);
                                  }
                                  /// <summary>
                                  /// Can be invoked to trigger the SendFromClientToServerWithoutReturnType on the <see cref = "IBasicHub"/>.
                                  /// </summary>
                                  /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="BasicHubClient.StartAsync"/></exception>
                                  public global::System.Threading.Tasks.Task InvokeSendFromClientToServerWithoutReturnTypeAsync(string message, global::System.Threading.CancellationToken ct = default)
                                  {
                                      ValidateHubConnection();
                                      return InvokeCoreAsync("SendFromClientToServerWithoutReturnType", new object?[] { message }, cancellationToken: ct);
                                  }
                                  /// <summary>
                                  /// Can be invoked to trigger the SendFromClientToServerPrimitiveTypes on the <see cref = "IBasicHub"/>.
                                  /// </summary>
                                  /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="BasicHubClient.StartAsync"/></exception>
                                  public global::System.Threading.Tasks.Task<bool> InvokeSendFromClientToServerPrimitiveTypesAsync(string foo, int bar, global::System.Threading.CancellationToken ct = default)
                                  {
                                      ValidateHubConnection();
                                      return InvokeCoreAsync<bool>("SendFromClientToServerPrimitiveTypes", new object?[] { foo, bar }, cancellationToken: ct);
                                  }
                                  
                                  protected override void RegisterHubMethods()
                                  {
                                      if (_hubConnection is null)
                                      {
                                          return;
                                      }
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Clients.BasicMessage>(_hubConnection, "SendFromServerToClientMessage", SendFromServerToClientMessageHandler);
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage>>(_hubConnection, "SendFromServerToClientWithList", SendFromServerToClientWithListHandler);
                                      global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "SendFromServerToClientPrimitiveTypes", SendFromServerToClientPrimitiveTypesHandler);
                                  }
                                  
                                  private void ValidateHubConnection()
                                  {
                                      if (_hubConnection is null)
                                      {
                                          throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
                                      }
                                  }
                              }
                              
                              public record BasicMessage(string Message, BasicMessageType Type, DateTimeOffset Timestamp);
                              
                              public enum BasicMessageType
                              {
                                  Info,
                                  Warning,
                                  Error
                              }
                              
                              public record BasicReturn(BasicMessage Message);
                              """;
        
        return TestHelper.Verify(source);
    }
}