//HintName: GenericTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Generator;
using SignalRGen.Generator.Tests.TestData;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IGenericTestHubClient"/> interface.
/// </summary>
public class GenericTestHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "generics";
    public GenericTestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveGenericList of the <see cref = "IGenericTestHubClient"/> gets invoked.
    /// </summary>
    public Func<List<CustomTypeDto>, Task>? OnReceiveGenericList = default;
    private Task ReceiveGenericListHandler(List<CustomTypeDto> items)
    {
        return OnReceiveGenericList?.Invoke(items) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveDictionary of the <see cref = "IGenericTestHubClient"/> gets invoked.
    /// </summary>
    public Func<Dictionary<string, int>, Task>? OnReceiveDictionary = default;
    private Task ReceiveDictionaryHandler(Dictionary<string, int> keyValuePairs)
    {
        return OnReceiveDictionary?.Invoke(keyValuePairs) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedGeneric of the <see cref = "IGenericTestHubClient"/> gets invoked.
    /// </summary>
    public Func<Dictionary<string, List<CustomTypeDto>>, Task>? OnReceiveNestedGeneric = default;
    private Task ReceiveNestedGenericHandler(Dictionary<string, List<CustomTypeDto>> complexData)
    {
        return OnReceiveNestedGeneric?.Invoke(complexData) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method SendAndReceiveGeneric of the <see cref = "IGenericTestHubClient"/> gets invoked.
    /// </summary>
    public Func<List<CustomTypeDto>, Task>? OnSendAndReceiveGeneric = default;
    private Task SendAndReceiveGenericHandler(List<CustomTypeDto> input)
    {
        return OnSendAndReceiveGeneric?.Invoke(input) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendNestedTask on the <see cref = "IGenericTestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="GenericTestHubClient.StartAsync"/></exception>
    public Task<Task<string>> InvokeSendNestedTaskAsync(Task<int> nestedTask, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<<string>>("SendNestedTask", nestedTask, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<List<CustomTypeDto>>("ReceiveGenericList", ReceiveGenericListHandler);
	    _hubConnection?.On<Dictionary<string, int>>("ReceiveDictionary", ReceiveDictionaryHandler);
	    _hubConnection?.On<Dictionary<string, List<CustomTypeDto>>>("ReceiveNestedGeneric", ReceiveNestedGenericHandler);
	    _hubConnection?.On<List<CustomTypeDto>>("SendAndReceiveGeneric", SendAndReceiveGenericHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}