//HintName: LongMethodNamesTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.ILongMethodNamesTestHub"/> interface.
/// </summary>
public class LongMethodNamesTestHubClient : HubClientBase
{
    public static string HubUri { get; } = "longmethods";
    public LongMethodNamesTestHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming of the <see cref = "global::SignalRGen.Clients.ILongMethodNamesTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<string, global::System.Threading.Tasks.Task>? OnReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming = default;
    private global::System.Threading.Tasks.Task ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNamingHandler(string message)
    {
        return OnReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming?.Invoke(message) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAnotherVeryLongMethodNameWithMultipleParametersAndComplexSignature on the <see cref = "ILongMethodNamesTestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="LongMethodNamesTestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendAnotherVeryLongMethodNameWithMultipleParametersAndComplexSignatureAsync(string firstParam, int secondParam, bool thirdParam, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendAnotherVeryLongMethodNameWithMultipleParametersAndComplexSignature", new object?[] { firstParam, secondParam, thirdParam }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the RequestVeryLongMethodNameWithReturnTypeAndMultipleComplexParameters on the <see cref = "ILongMethodNamesTestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="LongMethodNamesTestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeRequestVeryLongMethodNameWithReturnTypeAndMultipleComplexParametersAsync(Dictionary<string, List<int>> complexParam, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("RequestVeryLongMethodNameWithReturnTypeAndMultipleComplexParameters", new object?[] { complexParam }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string>(_hubConnection, "ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming", ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNamingHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}