//HintName: TestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Generator;
using SignalRGen.Generator.Tests.TestData;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "ITestHubClient"/> interface.
/// </summary>
public class TestHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "examples";
    public TestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method NotifyNoAttributeApplied of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<Task>? OnNotifyNoAttributeApplied = default;
    private Task NotifyNoAttributeAppliedHandler()
    {
        return OnNotifyNoAttributeApplied?.Invoke() ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyServerToClient of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<Task>? OnNotifyServerToClient = default;
    private Task NotifyServerToClientHandler()
    {
        return OnNotifyServerToClient?.Invoke() ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyWithReturnNoAttributeApplied of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<Task>? OnNotifyWithReturnNoAttributeApplied = default;
    private Task NotifyWithReturnNoAttributeAppliedHandler()
    {
        return OnNotifyWithReturnNoAttributeApplied?.Invoke() ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyWithReturnServerToClient of the <see cref = "ITestHubClient"/> gets invoked.
    /// </summary>
    public Func<Task>? OnNotifyWithReturnServerToClient = default;
    private Task NotifyWithReturnServerToClientHandler()
    {
        return OnNotifyWithReturnServerToClient?.Invoke() ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the NotifyClientToServer on the <see cref = "ITestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public Task InvokeNotifyClientToServerAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("NotifyClientToServer", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the NotifyWithReturnClientToServer on the <see cref = "ITestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public Task<string> InvokeNotifyWithReturnClientToServerAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string>("NotifyWithReturnClientToServer", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On("NotifyNoAttributeApplied", NotifyNoAttributeAppliedHandler);
	    _hubConnection?.On("NotifyServerToClient", NotifyServerToClientHandler);
	    _hubConnection?.On("NotifyWithReturnNoAttributeApplied", NotifyWithReturnNoAttributeAppliedHandler);
	    _hubConnection?.On("NotifyWithReturnServerToClient", NotifyWithReturnServerToClientHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}