//HintName: NullableTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "INullableTestHub"/> interface.
/// </summary>
public class NullableTestHubClient : HubClientBase
{
    public static string HubUri { get; } = "nullables";
    public NullableTestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableString of the <see cref = "INullableTestHub"/> gets invoked.
    /// </summary>
    public Func<string?, Task>? OnReceiveNullableString = default;
    private Task ReceiveNullableStringHandler(string? nullableMessage)
    {
        return OnReceiveNullableString?.Invoke(nullableMessage) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableInt of the <see cref = "INullableTestHub"/> gets invoked.
    /// </summary>
    public Func<int?, Task>? OnReceiveNullableInt = default;
    private Task ReceiveNullableIntHandler(int? nullableNumber)
    {
        return OnReceiveNullableInt?.Invoke(nullableNumber) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableCustomType of the <see cref = "INullableTestHub"/> gets invoked.
    /// </summary>
    public Func<SignalRGen.Generator.Tests.TestData.CustomTypeDto?, Task>? OnReceiveNullableCustomType = default;
    private Task ReceiveNullableCustomTypeHandler(SignalRGen.Generator.Tests.TestData.CustomTypeDto? nullableDto)
    {
        return OnReceiveNullableCustomType?.Invoke(nullableDto) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyWithNullableArray of the <see cref = "INullableTestHub"/> gets invoked.
    /// </summary>
    public Func<string[]?, Task>? OnNotifyWithNullableArray = default;
    private Task NotifyWithNullableArrayHandler(string[]? nullableArray)
    {
        return OnNotifyWithNullableArray?.Invoke(nullableArray) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAndReceiveNullable on the <see cref = "INullableTestHub"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="NullableTestHubClient.StartAsync"/></exception>
    public Task<string?> InvokeSendAndReceiveNullableAsync(int? input, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string?>("SendAndReceiveNullable", input, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string?>("ReceiveNullableString", ReceiveNullableStringHandler);
	    _hubConnection?.On<int?>("ReceiveNullableInt", ReceiveNullableIntHandler);
	    _hubConnection?.On<SignalRGen.Generator.Tests.TestData.CustomTypeDto?>("ReceiveNullableCustomType", ReceiveNullableCustomTypeHandler);
	    _hubConnection?.On<string[]?>("NotifyWithNullableArray", NotifyWithNullableArrayHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}