//HintName: ArrayTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IArrayTestHub"/> interface.
/// </summary>
public class ArrayTestHubClient : HubClientBase
{
    public static string HubUri { get; } = "arrays";
    public ArrayTestHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveStringArray of the <see cref = "global::SignalRGen.Clients.IArrayTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<string[], global::System.Threading.Tasks.Task>? OnReceiveStringArray = default;
    private global::System.Threading.Tasks.Task ReceiveStringArrayHandler(string[] messages)
    {
        return OnReceiveStringArray?.Invoke(messages) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveIntArray of the <see cref = "global::SignalRGen.Clients.IArrayTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<int[], global::System.Threading.Tasks.Task>? OnReceiveIntArray = default;
    private global::System.Threading.Tasks.Task ReceiveIntArrayHandler(int[] numbers)
    {
        return OnReceiveIntArray?.Invoke(numbers) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeArray of the <see cref = "global::SignalRGen.Clients.IArrayTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto[], global::System.Threading.Tasks.Task>? OnReceiveCustomTypeArray = default;
    private global::System.Threading.Tasks.Task ReceiveCustomTypeArrayHandler(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto[] dtos)
    {
        return OnReceiveCustomTypeArray?.Invoke(dtos) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveMultidimensionalArray of the <see cref = "global::SignalRGen.Clients.IArrayTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<int[,], global::System.Threading.Tasks.Task>? OnReceiveMultidimensionalArray = default;
    private global::System.Threading.Tasks.Task ReceiveMultidimensionalArrayHandler(int[,] matrix)
    {
        return OnReceiveMultidimensionalArray?.Invoke(matrix) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveJaggedArray of the <see cref = "global::SignalRGen.Clients.IArrayTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<string[][], global::System.Threading.Tasks.Task>? OnReceiveJaggedArray = default;
    private global::System.Threading.Tasks.Task ReceiveJaggedArrayHandler(string[][] jaggedArray)
    {
        return OnReceiveJaggedArray?.Invoke(jaggedArray) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAndReceiveArray on the <see cref = "IArrayTestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ArrayTestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string[]> InvokeSendAndReceiveArrayAsync(int[] input, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string[]>("SendAndReceiveArray", new object?[] { input }, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string[]>(_hubConnection, "ReceiveStringArray", ReceiveStringArrayHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<int[]>(_hubConnection, "ReceiveIntArray", ReceiveIntArrayHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto[]>(_hubConnection, "ReceiveCustomTypeArray", ReceiveCustomTypeArrayHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<int[,]>(_hubConnection, "ReceiveMultidimensionalArray", ReceiveMultidimensionalArrayHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string[][]>(_hubConnection, "ReceiveJaggedArray", ReceiveJaggedArrayHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}