//HintName: ArrayTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Generator;
using SignalRGen.Generator.Tests.TestData;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IArrayTestHubClient"/> interface.
/// </summary>
public class ArrayTestHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "arrays";
    public ArrayTestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveStringArray of the <see cref = "IArrayTestHubClient"/> gets invoked.
    /// </summary>
    public Func<string[], Task>? OnReceiveStringArray = default;
    private Task ReceiveStringArrayHandler(string[] messages)
    {
        return OnReceiveStringArray?.Invoke(messages) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveIntArray of the <see cref = "IArrayTestHubClient"/> gets invoked.
    /// </summary>
    public Func<int[], Task>? OnReceiveIntArray = default;
    private Task ReceiveIntArrayHandler(int[] numbers)
    {
        return OnReceiveIntArray?.Invoke(numbers) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeArray of the <see cref = "IArrayTestHubClient"/> gets invoked.
    /// </summary>
    public Func<CustomTypeDto[], Task>? OnReceiveCustomTypeArray = default;
    private Task ReceiveCustomTypeArrayHandler(CustomTypeDto[] dtos)
    {
        return OnReceiveCustomTypeArray?.Invoke(dtos) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveMultidimensionalArray of the <see cref = "IArrayTestHubClient"/> gets invoked.
    /// </summary>
    public Func<int[,], Task>? OnReceiveMultidimensionalArray = default;
    private Task ReceiveMultidimensionalArrayHandler(int[,] matrix)
    {
        return OnReceiveMultidimensionalArray?.Invoke(matrix) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveJaggedArray of the <see cref = "IArrayTestHubClient"/> gets invoked.
    /// </summary>
    public Func<string[][], Task>? OnReceiveJaggedArray = default;
    private Task ReceiveJaggedArrayHandler(string[][] jaggedArray)
    {
        return OnReceiveJaggedArray?.Invoke(jaggedArray) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAndReceiveArray on the <see cref = "IArrayTestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ArrayTestHubClient.StartAsync"/></exception>
    public Task<string[]> InvokeSendAndReceiveArrayAsync(int[] input, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string[]>("SendAndReceiveArray", input, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string[]>("ReceiveStringArray", ReceiveStringArrayHandler);
	    _hubConnection?.On<int[]>("ReceiveIntArray", ReceiveIntArrayHandler);
	    _hubConnection?.On<CustomTypeDto[]>("ReceiveCustomTypeArray", ReceiveCustomTypeArrayHandler);
	    _hubConnection?.On<int[,]>("ReceiveMultidimensionalArray", ReceiveMultidimensionalArrayHandler);
	    _hubConnection?.On<string[][]>("ReceiveJaggedArray", ReceiveJaggedArrayHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}