//HintName: TestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.ITestHub"/> interface.
/// </summary>
public class TestHubClient : HubClientBase
{
    public static string HubUri { get; } = "examples";
    public TestHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeUpdate of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveCustomTypeUpdateDelegate(IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> customTypes);
    public ReceiveCustomTypeUpdateDelegate? OnReceiveCustomTypeUpdate = default;
    
    private global::System.Threading.Tasks.Task ReceiveCustomTypeUpdateHandler(IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> customTypes)
    {
        return OnReceiveCustomTypeUpdate?.Invoke(customTypes) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveFooUpdate of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveFooUpdateDelegate(string bar, int bass);
    public ReceiveFooUpdateDelegate? OnReceiveFooUpdate = default;
    
    private global::System.Threading.Tasks.Task ReceiveFooUpdateHandler(string bar, int bass)
    {
        return OnReceiveFooUpdate?.Invoke(bar, bass) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNormalTypeWithSpecificAttributeApplied of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveNormalTypeWithSpecificAttributeAppliedDelegate(string bazz, int buzz);
    public ReceiveNormalTypeWithSpecificAttributeAppliedDelegate? OnReceiveNormalTypeWithSpecificAttributeApplied = default;
    
    private global::System.Threading.Tasks.Task ReceiveNormalTypeWithSpecificAttributeAppliedHandler(string bazz, int buzz)
    {
        return OnReceiveNormalTypeWithSpecificAttributeApplied?.Invoke(bazz, buzz) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveWithArbitraryAttribute of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveWithArbitraryAttributeDelegate(int blub);
    public ReceiveWithArbitraryAttributeDelegate? OnReceiveWithArbitraryAttribute = default;
    
    private global::System.Threading.Tasks.Task ReceiveWithArbitraryAttributeHandler(int blub)
    {
        return OnReceiveWithArbitraryAttribute?.Invoke(blub) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendClientToServerNoReturnType on the <see cref = "ITestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendClientToServerNoReturnTypeAsync(string rick, int age, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendClientToServerNoReturnType", new object?[] { rick, age }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the SendClientToServerWithReturnType on the <see cref = "ITestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeSendClientToServerWithReturnTypeAsync(string morty, bool partOfMission, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("SendClientToServerWithReturnType", new object?[] { morty, partOfMission }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>>(_hubConnection, "ReceiveCustomTypeUpdate", ReceiveCustomTypeUpdateHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "ReceiveFooUpdate", ReceiveFooUpdateHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "ReceiveNormalTypeWithSpecificAttributeApplied", ReceiveNormalTypeWithSpecificAttributeAppliedHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<int>(_hubConnection, "ReceiveWithArbitraryAttribute", ReceiveWithArbitraryAttributeHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}