//HintName: TestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.ITestHub"/> interface.
/// </summary>
public class TestHubClient : HubClientBase
{
    public static string HubUri { get; } = "examples";
    public TestHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method NotifyNoAttributeApplied of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task NotifyNoAttributeAppliedDelegate();
    public NotifyNoAttributeAppliedDelegate? OnNotifyNoAttributeApplied = default;
    
    private global::System.Threading.Tasks.Task NotifyNoAttributeAppliedHandler()
    {
        return OnNotifyNoAttributeApplied?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyServerToClient of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task NotifyServerToClientDelegate();
    public NotifyServerToClientDelegate? OnNotifyServerToClient = default;
    
    private global::System.Threading.Tasks.Task NotifyServerToClientHandler()
    {
        return OnNotifyServerToClient?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyWithReturnNoAttributeApplied of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task NotifyWithReturnNoAttributeAppliedDelegate();
    public NotifyWithReturnNoAttributeAppliedDelegate? OnNotifyWithReturnNoAttributeApplied = default;
    
    private global::System.Threading.Tasks.Task NotifyWithReturnNoAttributeAppliedHandler()
    {
        return OnNotifyWithReturnNoAttributeApplied?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyWithReturnServerToClient of the <see cref = "global::SignalRGen.Clients.ITestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task NotifyWithReturnServerToClientDelegate();
    public NotifyWithReturnServerToClientDelegate? OnNotifyWithReturnServerToClient = default;
    
    private global::System.Threading.Tasks.Task NotifyWithReturnServerToClientHandler()
    {
        return OnNotifyWithReturnServerToClient?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the NotifyClientToServer on the <see cref = "ITestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeNotifyClientToServerAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("NotifyClientToServer", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the NotifyWithReturnClientToServer on the <see cref = "ITestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="TestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeNotifyWithReturnClientToServerAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("NotifyWithReturnClientToServer", cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "NotifyNoAttributeApplied", NotifyNoAttributeAppliedHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "NotifyServerToClient", NotifyServerToClientHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "NotifyWithReturnNoAttributeApplied", NotifyWithReturnNoAttributeAppliedHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "NotifyWithReturnServerToClient", NotifyWithReturnServerToClientHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}