//HintName: GenericTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.IGenericTestHub"/> interface.
/// </summary>
public class GenericTestHubClient : HubClientBase
{
    public static string HubUri { get; } = "generics";
    public GenericTestHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveGenericList of the <see cref = "global::SignalRGen.Clients.IGenericTestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveGenericListDelegate(List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> items);
    public ReceiveGenericListDelegate? OnReceiveGenericList = default;
    
    private global::System.Threading.Tasks.Task ReceiveGenericListHandler(List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> items)
    {
        return OnReceiveGenericList?.Invoke(items) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveDictionary of the <see cref = "global::SignalRGen.Clients.IGenericTestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveDictionaryDelegate(Dictionary<string, int> keyValuePairs);
    public ReceiveDictionaryDelegate? OnReceiveDictionary = default;
    
    private global::System.Threading.Tasks.Task ReceiveDictionaryHandler(Dictionary<string, int> keyValuePairs)
    {
        return OnReceiveDictionary?.Invoke(keyValuePairs) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedGeneric of the <see cref = "global::SignalRGen.Clients.IGenericTestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveNestedGenericDelegate(Dictionary<string, List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>> complexData);
    public ReceiveNestedGenericDelegate? OnReceiveNestedGeneric = default;
    
    private global::System.Threading.Tasks.Task ReceiveNestedGenericHandler(Dictionary<string, List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>> complexData)
    {
        return OnReceiveNestedGeneric?.Invoke(complexData) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method SendAndReceiveGeneric of the <see cref = "global::SignalRGen.Clients.IGenericTestHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task SendAndReceiveGenericDelegate(List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> input);
    public SendAndReceiveGenericDelegate? OnSendAndReceiveGeneric = default;
    
    private global::System.Threading.Tasks.Task SendAndReceiveGenericHandler(List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> input)
    {
        return OnSendAndReceiveGeneric?.Invoke(input) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendNestedTask on the <see cref = "IGenericTestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="GenericTestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<global::System.Threading.Tasks.Task<string>> InvokeSendNestedTaskAsync(global::System.Threading.Tasks.Task<int> nestedTask, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<global::System.Threading.Tasks.Task<string>>("SendNestedTask", new object?[] { nestedTask }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>>(_hubConnection, "ReceiveGenericList", ReceiveGenericListHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<Dictionary<string, int>>(_hubConnection, "ReceiveDictionary", ReceiveDictionaryHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<Dictionary<string, List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>>>(_hubConnection, "ReceiveNestedGeneric", ReceiveNestedGenericHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>>(_hubConnection, "SendAndReceiveGeneric", SendAndReceiveGenericHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}