//HintName: ValueTupleTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IValueTupleTestHub"/> interface.
/// </summary>
public class ValueTupleTestHubClient : HubClientBase
{
    public static string HubUri { get; } = "valuetuples";
    public ValueTupleTestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveTuple of the <see cref = "IValueTupleTestHub"/> gets invoked.
    /// </summary>
    public Func<(string name, int age), Task>? OnReceiveTuple = default;
    private Task ReceiveTupleHandler((string name, int age) person)
    {
        return OnReceiveTuple?.Invoke(person) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedTuple of the <see cref = "IValueTupleTestHub"/> gets invoked.
    /// </summary>
    public Func<(string, (int, bool)), Task>? OnReceiveNestedTuple = default;
    private Task ReceiveNestedTupleHandler((string, (int, bool)) complexTuple)
    {
        return OnReceiveNestedTuple?.Invoke(complexTuple) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNamedTuple of the <see cref = "IValueTupleTestHub"/> gets invoked.
    /// </summary>
    public Func<(string FirstName, string LastName, int Age), Task>? OnReceiveNamedTuple = default;
    private Task ReceiveNamedTupleHandler((string FirstName, string LastName, int Age) person)
    {
        return OnReceiveNamedTuple?.Invoke(person) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAndReceiveTuple on the <see cref = "IValueTupleTestHub"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ValueTupleTestHubClient.StartAsync"/></exception>
    public Task<(bool success, string message)> InvokeSendAndReceiveTupleAsync((int id, string data) input, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<(bool success, string message)>("SendAndReceiveTuple", input, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<(string name, int age)>("ReceiveTuple", ReceiveTupleHandler);
	    _hubConnection?.On<(string, (int, bool))>("ReceiveNestedTuple", ReceiveNestedTupleHandler);
	    _hubConnection?.On<(string FirstName, string LastName, int Age)>("ReceiveNamedTuple", ReceiveNamedTupleHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}