//HintName: LongMethodNamesTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Generator;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "ILongMethodNamesTestHubClient"/> interface.
/// </summary>
public class LongMethodNamesTestHubClient : HubClientBase, IHubClient
{
    public static string HubUri { get; } = "longmethods";
    public LongMethodNamesTestHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming of the <see cref = "ILongMethodNamesTestHubClient"/> gets invoked.
    /// </summary>
    public Func<string, Task>? OnReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming = default;
    private Task ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNamingHandler(string message)
    {
        return OnReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming?.Invoke(message) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAnotherVeryLongMethodNameWithMultipleParametersAndComplexSignature on the <see cref = "ILongMethodNamesTestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="LongMethodNamesTestHubClient.StartAsync"/></exception>
    public Task InvokeSendAnotherVeryLongMethodNameWithMultipleParametersAndComplexSignatureAsync(string firstParam, int secondParam, bool thirdParam, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendAnotherVeryLongMethodNameWithMultipleParametersAndComplexSignature", firstParam, secondParam, thirdParam, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the RequestVeryLongMethodNameWithReturnTypeAndMultipleComplexParameters on the <see cref = "ILongMethodNamesTestHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="LongMethodNamesTestHubClient.StartAsync"/></exception>
    public Task<string> InvokeRequestVeryLongMethodNameWithReturnTypeAndMultipleComplexParametersAsync(Dictionary<string, List<int>> complexParam, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string>("RequestVeryLongMethodNameWithReturnTypeAndMultipleComplexParameters", complexParam, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string>("ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNaming", ReceiveVeryLongMethodNameThatExceedsNormalExpectationsForMethodNamingHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}