//HintName: NullableTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.INullableTestHub"/> interface.
/// </summary>
public class NullableTestHubClient : HubClientBase
{
    public static string HubUri { get; } = "nullables";
    public NullableTestHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableString of the <see cref = "global::SignalRGen.Clients.INullableTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<string, global::System.Threading.Tasks.Task>? OnReceiveNullableString = default;
    private global::System.Threading.Tasks.Task ReceiveNullableStringHandler(string nullableMessage)
    {
        return OnReceiveNullableString?.Invoke(nullableMessage) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableInt of the <see cref = "global::SignalRGen.Clients.INullableTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<int?, global::System.Threading.Tasks.Task>? OnReceiveNullableInt = default;
    private global::System.Threading.Tasks.Task ReceiveNullableIntHandler(int? nullableNumber)
    {
        return OnReceiveNullableInt?.Invoke(nullableNumber) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableCustomType of the <see cref = "global::SignalRGen.Clients.INullableTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto, global::System.Threading.Tasks.Task>? OnReceiveNullableCustomType = default;
    private global::System.Threading.Tasks.Task ReceiveNullableCustomTypeHandler(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto nullableDto)
    {
        return OnReceiveNullableCustomType?.Invoke(nullableDto) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method NotifyWithNullableArray of the <see cref = "global::SignalRGen.Clients.INullableTestHub"/> gets invoked.
    /// </summary>
    public global::System.Func<string[], global::System.Threading.Tasks.Task>? OnNotifyWithNullableArray = default;
    private global::System.Threading.Tasks.Task NotifyWithNullableArrayHandler(string[] nullableArray)
    {
        return OnNotifyWithNullableArray?.Invoke(nullableArray) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendAndReceiveNullable on the <see cref = "INullableTestHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="NullableTestHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeSendAndReceiveNullableAsync(int? input, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("SendAndReceiveNullable", new object?[] { input }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string>(_hubConnection, "ReceiveNullableString", ReceiveNullableStringHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<int?>(_hubConnection, "ReceiveNullableInt", ReceiveNullableIntHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>(_hubConnection, "ReceiveNullableCustomType", ReceiveNullableCustomTypeHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string[]>(_hubConnection, "NotifyWithNullableArray", NotifyWithNullableArrayHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}