//HintName: DefaultHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace MyCompany.App.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IDefaultHub"/> interface.
/// </summary>
public class DefaultHubClient : HubClientBase
{
    public static string HubUri { get; } = "default";
    public DefaultHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method Notify of the <see cref = "IDefaultHub"/> gets invoked.
    /// </summary>
    public Func<Task>? OnNotify = default;
    private Task NotifyHandler()
    {
        return OnNotify?.Invoke() ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the Ack on the <see cref = "IDefaultHub"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="DefaultHubClient.StartAsync"/></exception>
    public Task InvokeAckAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("Ack", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On("Notify", NotifyHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}