//HintName: DefaultHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyCompany.App.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::MyCompany.App.Clients.IDefaultHub"/> interface.
/// </summary>
public class DefaultHubClient : HubClientBase
{
    public static string HubUri { get; } = "default";
    public DefaultHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method Notify of the <see cref = "global::MyCompany.App.Clients.IDefaultHub"/> gets invoked.
    /// </summary>
    public global::System.Func<global::System.Threading.Tasks.Task>? OnNotify = default;
    private global::System.Threading.Tasks.Task NotifyHandler()
    {
        return OnNotify?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the Ack on the <see cref = "IDefaultHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="DefaultHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeAckAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("Ack", cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "Notify", NotifyHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}