//HintName: PingHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MyCompany.App.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::MyCompany.App.Clients.IPingHub"/> interface.
/// </summary>
public class PingHubClient : HubClientBase
{
    public static string HubUri { get; } = "ping";
    public PingHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method Ping of the <see cref = "global::MyCompany.App.Clients.IPingHub"/> gets invoked.
    /// </summary>
    public global::System.Func<global::System.Threading.Tasks.Task>? OnPing = default;
    private global::System.Threading.Tasks.Task PingHandler()
    {
        return OnPing?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the Pong on the <see cref = "IPingHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="PingHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokePongAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("Pong", cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "Ping", PingHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}