//HintName: PingHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace MyCompany.App.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IPingHub"/> interface.
/// </summary>
public class PingHubClient : HubClientBase
{
    public static string HubUri { get; } = "ping";
    public PingHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method Ping of the <see cref = "IPingHub"/> gets invoked.
    /// </summary>
    public Func<Task>? OnPing = default;
    private Task PingHandler()
    {
        return OnPing?.Invoke() ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the Pong on the <see cref = "IPingHub"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="PingHubClient.StartAsync"/></exception>
    public Task InvokePongAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("Pong", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On("Ping", PingHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}