//HintName: NestedCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients.Nested;

/// <summary>
/// Represents a HubClient for the <see cref = "INestedCommandHubClient"/> interface.
/// </summary>
public class NestedCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "nested-commands";
    public NestedCommandHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the SendNestedCommand on the <see cref = "INestedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="NestedCommandHubClient.StartAsync"/></exception>
    public Task InvokeSendNestedCommandAsync(string command, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendNestedCommand", command, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetNestedData on the <see cref = "INestedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="NestedCommandHubClient.StartAsync"/></exception>
    public Task<SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetNestedDataAsync(int id, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetNestedData", id, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}