//HintName: VoidCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IVoidCommandHubClient"/> interface.
/// </summary>
public class VoidCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "void-commands";
    public VoidCommandHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the SendNotification on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendNotificationAsync(string message, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendNotification", new object?[] { message }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the UpdateStatus on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeUpdateStatusAsync(bool isOnline, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("UpdateStatus", new object?[] { isOnline }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the LogActivity on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeLogActivityAsync(string activity, global::SignalRGen.Generator.Tests.TestData.CustomTypeDto context, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("LogActivity", new object?[] { activity, context }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the ClearCache on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeClearCacheAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("ClearCache", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}