//HintName: CommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.ICommandHubClient"/> interface.
/// </summary>
public class CommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "commands";
    public CommandHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    

    /// <summary>
    /// Can be invoked to trigger the SendCommand on the <see cref = "ICommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="CommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendCommandAsync(string command, string payload, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendCommand", new object?[] { command, payload }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the RequestData on the <see cref = "ICommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="CommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeRequestDataAsync(int id, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("RequestData", new object?[] { id }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetCustomData on the <see cref = "ICommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="CommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetCustomDataAsync(string filter, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetCustomData", new object?[] { filter }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}