//HintName: ParameterlessCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IParameterlessCommandHubClient"/> interface.
/// </summary>
public class ParameterlessCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "parameterless-commands";
    public ParameterlessCommandHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the Ping on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public Task InvokePingAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("Ping", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the Disconnect on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public Task InvokeDisconnectAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("Disconnect", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetServerTime on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public Task<string> InvokeGetServerTimeAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string>("GetServerTime", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetServerStatus on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public Task<SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetServerStatusAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetServerStatus", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the IsAlive on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public Task<bool> InvokeIsAliveAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<bool>("IsAlive", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}