//HintName: ComplexCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.IComplexCommandHubClient"/> interface.
/// </summary>
public class ComplexCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "complex-commands";
    public ComplexCommandHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    

    /// <summary>
    /// Can be invoked to trigger the SendUserData on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendUserDataAsync(List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> users, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendUserData", new object?[] { users }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetMetrics on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<Dictionary<string, int>> InvokeGetMetricsAsync(string filter, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<Dictionary<string, int>>("GetMetrics", new object?[] { filter }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the RequestStringArray on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string[]> InvokeRequestStringArrayAsync(int count, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string[]>("RequestStringArray", new object?[] { count }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the ProcessTupleData on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<(bool success, string message)> InvokeProcessTupleDataAsync((int id, string data) input, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<(bool success, string message)>("ProcessTupleData", new object?[] { input }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the SendNullableData on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendNullableDataAsync(string nullableMessage, int? nullableCount, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendNullableData", new object?[] { nullableMessage, nullableCount }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}