//HintName: VoidCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IVoidCommandHubClient"/> interface.
/// </summary>
public class VoidCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "void-commands";
    public VoidCommandHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the SendNotification on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public Task InvokeSendNotificationAsync(string message, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendNotification", message, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the UpdateStatus on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public Task InvokeUpdateStatusAsync(bool isOnline, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("UpdateStatus", isOnline, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the LogActivity on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public Task InvokeLogActivityAsync(string activity, SignalRGen.Generator.Tests.TestData.CustomTypeDto context, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("LogActivity", activity, context, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the ClearCache on the <see cref = "IVoidCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="VoidCommandHubClient.StartAsync"/></exception>
    public Task InvokeClearCacheAsync(CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("ClearCache", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}