//HintName: ComplexCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IComplexCommandHubClient"/> interface.
/// </summary>
public class ComplexCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "complex-commands";
    public ComplexCommandHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the SendUserData on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public Task InvokeSendUserDataAsync(List<SignalRGen.Generator.Tests.TestData.CustomTypeDto> users, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendUserData", users, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetMetrics on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public Task<Dictionary<string, int>> InvokeGetMetricsAsync(string filter, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<Dictionary<string, int>>("GetMetrics", filter, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the RequestStringArray on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public Task<string[]> InvokeRequestStringArrayAsync(int count, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string[]>("RequestStringArray", count, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the ProcessTupleData on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public Task<(bool success, string message)> InvokeProcessTupleDataAsync((int id, string data) input, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<(bool success, string message)>("ProcessTupleData", input, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the SendNullableData on the <see cref = "IComplexCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ComplexCommandHubClient.StartAsync"/></exception>
    public Task InvokeSendNullableDataAsync(string? nullableMessage, int? nullableCount, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendNullableData", nullableMessage, nullableCount, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}