//HintName: ParameterlessCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IParameterlessCommandHubClient"/> interface.
/// </summary>
public class ParameterlessCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "parameterless-commands";
    public ParameterlessCommandHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the Ping on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokePingAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("Ping", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the Disconnect on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeDisconnectAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("Disconnect", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetServerTime on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeGetServerTimeAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("GetServerTime", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetServerStatus on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetServerStatusAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetServerStatus", cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the IsAlive on the <see cref = "IParameterlessCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ParameterlessCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<bool> InvokeIsAliveAsync(global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<bool>("IsAlive", cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}