//HintName: ExtendedCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IExtendedCommandHubClient"/> interface.
/// </summary>
public class ExtendedCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "extended-commands";
    public ExtendedCommandHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    


    /// <summary>
    /// Can be invoked to trigger the SendExtendedCommand on the <see cref = "IExtendedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExtendedCommandHubClient.StartAsync"/></exception>
    public Task InvokeSendExtendedCommandAsync(string command, string payload, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync("SendExtendedCommand", command, payload, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetExtendedData on the <see cref = "IExtendedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExtendedCommandHubClient.StartAsync"/></exception>
    public Task<SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetExtendedDataAsync(string filter, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetExtendedData", filter, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetBaseData on the <see cref = "IExtendedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExtendedCommandHubClient.StartAsync"/></exception>
    public Task<string> InvokeGetBaseDataAsync(int id, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<string>("GetBaseData", id, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
    
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}