//HintName: NestedCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients.Nested;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.Nested.INestedCommandHubClient"/> interface.
/// </summary>
public class NestedCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "nested-commands";
    public NestedCommandHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    

    /// <summary>
    /// Can be invoked to trigger the SendNestedCommand on the <see cref = "INestedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="NestedCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendNestedCommandAsync(string command, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendNestedCommand", new object?[] { command }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetNestedData on the <see cref = "INestedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="NestedCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetNestedDataAsync(int id, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetNestedData", new object?[] { id }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}