//HintName: ExtendedCommandHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.IExtendedCommandHubClient"/> interface.
/// </summary>
public class ExtendedCommandHubClient : HubClientBase
{
    public static string HubUri { get; } = "extended-commands";
    public ExtendedCommandHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    

    /// <summary>
    /// Can be invoked to trigger the SendExtendedCommand on the <see cref = "IExtendedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExtendedCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task InvokeSendExtendedCommandAsync(string command, string payload, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync("SendExtendedCommand", new object?[] { command, payload }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetExtendedData on the <see cref = "IExtendedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExtendedCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> InvokeGetExtendedDataAsync(string filter, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>("GetExtendedData", new object?[] { filter }, cancellationToken: ct);
    }
    /// <summary>
    /// Can be invoked to trigger the GetBaseData on the <see cref = "IExtendedCommandHubClient"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExtendedCommandHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<string> InvokeGetBaseDataAsync(int id, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<string>("GetBaseData", new object?[] { id }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}