//HintName: ServerToClientMethodAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace SignalRGen.Generator;

[AttributeUsage(AttributeTargets.Method)]
public sealed class ServerToClientMethodAttribute : Attribute
{
}