//HintName: SignalRClientServiceRegistration.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.DependencyInjection;
using SignalRGen.Generator.Client.Configuration;

#nullable enable

namespace SignalRGen.Generator.Client.Extensions.DependencyInjection;

public static class SignalRClientServiceRegistration
{
    /// <summary>
    /// Creates the base configuration for all registered Hubs. The Hubs you want to use must be registered with the appropriate `With{...}` call.
    /// </summary>
    /// <param name = "services">The services available in the application.</param>
    /// <param name = "generalConfiguration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "SignalRHubServiceCollection"/> to register the specified Hub.</returns>
    public static SignalRHubServiceCollection AddSignalRHubs(this IServiceCollection services, Action<SignalROptions> generalConfiguration)
    {
        ArgumentNullException.ThrowIfNull(generalConfiguration);
        var config = new SignalROptions();
        generalConfiguration.Invoke(config);
        return new SignalRHubServiceCollection(services, config);
    }


}