//HintName: ExampleHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Example.Contracts;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Example.Contracts.IExampleHub"/> interface.
/// </summary>
public class ExampleHubClient : HubClientBase
{
    public static string HubUri { get; } = "example";
    public ExampleHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveBaseMessage of the <see cref = "global::SignalRGen.Example.Contracts.IExampleHub"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveBaseMessageDelegate(string message);
    public ReceiveBaseMessageDelegate? OnReceiveBaseMessage = default;
    
    private global::System.Threading.Tasks.Task ReceiveBaseMessageHandler(string message)
    {
        return OnReceiveBaseMessage?.Invoke(message) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendBaseMessage on the <see cref = "IExampleHub"/>.
    /// </summary>
    /// <exception cref="global::System.InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExampleHubClient.StartAsync"/></exception>
    public global::System.Threading.Tasks.Task<int> InvokeSendBaseMessageAsync(string message, global::System.Threading.CancellationToken ct = default)
    {
        ValidateHubConnection();
        return InvokeCoreAsync<int>("SendBaseMessage", new object?[] { message }, cancellationToken: ct);
    }
    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string>(_hubConnection, "ReceiveBaseMessage", ReceiveBaseMessageHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}