//HintName: ExampleHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions.Attributes;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Example.Contracts;

/// <summary>
/// Represents a HubClient for the <see cref = "IExampleHubClient"/> interface.
/// </summary>
public class ExampleHubClient : HubClientBase
{
    public static string HubUri { get; } = "example";
    public ExampleHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveBaseMessage of the <see cref = "IExampleHubClient"/> gets invoked.
    /// </summary>
    public Func<string, Task>? OnReceiveBaseMessage = default;
    private Task ReceiveBaseMessageHandler(string message)
    {
        return OnReceiveBaseMessage?.Invoke(message) ?? Task.CompletedTask;
    }

    /// <summary>
    /// Can be invoked to trigger the SendBaseMessage on the <see cref = "IExampleHubClient"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown, when the Hub was not yet started by calling <see cref="ExampleHubClient.StartAsync"/></exception>
    public Task<int> InvokeSendBaseMessageAsync(string message, CancellationToken ct = default)
    {
        ValidateHubConnection();
        return _hubConnection!.InvokeAsync<int>("SendBaseMessage", message, cancellationToken: ct);
    }

    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string>("ReceiveBaseMessage", ReceiveBaseMessageHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}