//HintName: FakeBasicHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace SignalRGen.Clients.TestFakes;


public sealed class FakeBasicHubClient : SignalRGen.Clients.BasicHubClient
{
    private readonly global::System.Threading.Lock _lock = new();

    public global::System.Collections.Generic.IReadOnlyList<string> SendFromClientToServerMessageCalls
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_sendFromClientToServerMessageCalls); }
    }
    private readonly global::System.Collections.Generic.List<string> _sendFromClientToServerMessageCalls = new();

    
    public global::System.Func<string, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<global::SignalRGen.Clients.BasicReturn>>? SendFromClientToServerMessageHandler { get; set; }
    
    
    public global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.List<string>> SendFromClientToServerWithListCalls
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_sendFromClientToServerWithListCalls); }
    }
    private readonly global::System.Collections.Generic.List<global::System.Collections.Generic.List<string>> _sendFromClientToServerWithListCalls = new();

    
    public global::System.Func<global::System.Collections.Generic.List<string>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicReturn>>>? SendFromClientToServerWithListHandler { get; set; }
    
    
    public global::System.Collections.Generic.IReadOnlyList<string> SendFromClientToServerWithoutReturnTypeCalls
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_sendFromClientToServerWithoutReturnTypeCalls); }
    }
    private readonly global::System.Collections.Generic.List<string> _sendFromClientToServerWithoutReturnTypeCalls = new();

    
    public global::System.Func<string, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>? SendFromClientToServerWithoutReturnTypeHandler { get; set; }
    
    
    public global::System.Collections.Generic.IReadOnlyList<(string foo, int bar)> SendFromClientToServerPrimitiveTypesCalls
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_sendFromClientToServerPrimitiveTypesCalls); }
    }
    private readonly global::System.Collections.Generic.List<(string foo, int bar)> _sendFromClientToServerPrimitiveTypesCalls = new();
    
    public global::System.Func<string, int, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<bool>>? SendFromClientToServerPrimitiveTypesHandler { get; set; }
    
    


    public global::System.Collections.Generic.IReadOnlyList<global::SignalRGen.Clients.BasicMessage> OnSendFromServerToClientMessageEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onSendFromServerToClientMessageEvents); }
    }
    private readonly global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage> _onSendFromServerToClientMessageEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<global::SignalRGen.Clients.BasicMessage> _onSendFromServerToClientMessageChannel = new();


    public global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage>> OnSendFromServerToClientWithListEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onSendFromServerToClientWithListEvents); }
    }
    private readonly global::System.Collections.Generic.List<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage>> _onSendFromServerToClientWithListEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage>> _onSendFromServerToClientWithListChannel = new();


    public global::System.Collections.Generic.IReadOnlyList<(string arg1, int arg2)> OnSendFromServerToClientPrimitiveTypesEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onSendFromServerToClientPrimitiveTypesEvents); }
    }
    private readonly global::System.Collections.Generic.List<(string arg1, int arg2)> _onSendFromServerToClientPrimitiveTypesEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<(string arg1, int arg2)> _onSendFromServerToClientPrimitiveTypesChannel = new();

    /// <summary>
    /// When true, the fake client operates in strict mode:
    /// any unconfigured or unexpected invocation will throw an exception.
    /// Use to ensure tests explicitly define expected interactions.
    /// </summary>
    public bool Strict { get; set; }

    public FakeBasicHubClient(
             global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration = null,
             global::System.Uri? baseHubUri = null,
             global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration = null)
             : base(hubConnectionBuilderConfiguration, baseHubUri ?? new global::System.Uri("http://localhost/"), httpConnectionOptionsConfiguration)
    {
    }

    protected override void RegisterHubMethods()
    {
    }

    public override global::System.Threading.Tasks.Task StartAsync(
        global::System.Collections.Generic.Dictionary<string, string>? queryStrings = null,
        global::System.Collections.Generic.Dictionary<string, string>? headers = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var builder = new global::Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder();
        
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilderHttpExtensions
                                               .WithUrl(builder, "http://localhost");
        
        _hubConnection = builder.Build();
        
        return global::System.Threading.Tasks.Task.CompletedTask;
    }

    public override global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::System.Threading.Tasks.Task.CompletedTask;

    protected override async global::System.Threading.Tasks.Task InvokeCoreAsync(string methodName, object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        switch (methodName)
        {
            case "SendFromClientToServerWithoutReturnType":
                await HandleSendFromClientToServerWithoutReturnType(args, cancellationToken);
                return;
       
           default:
                if (Strict) throw new global::System.NotSupportedException($"Method '{methodName}' is not supported by the fake.");
                return;
        }
    }

    protected override async global::System.Threading.Tasks.Task<TResult> InvokeCoreAsync<TResult>(string methodName, object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        switch (methodName)
        {
            case "SendFromClientToServerMessage":
                var resultSendFromClientToServerMessage = await HandleSendFromClientToServerMessage(args, cancellationToken);
                return (TResult)(object)resultSendFromClientToServerMessage!;
            case "SendFromClientToServerWithList":
                var resultSendFromClientToServerWithList = await HandleSendFromClientToServerWithList(args, cancellationToken);
                return (TResult)(object)resultSendFromClientToServerWithList!;
            case "SendFromClientToServerPrimitiveTypes":
                var resultSendFromClientToServerPrimitiveTypes = await HandleSendFromClientToServerPrimitiveTypes(args, cancellationToken);
                return (TResult)(object)resultSendFromClientToServerPrimitiveTypes!;
       
           default:
                if (Strict) throw new global::System.NotSupportedException($"Method '{methodName}' is not supported by the fake.");
                return default!;
        }
    }

    private async global::System.Threading.Tasks.Task<global::SignalRGen.Clients.BasicReturn> HandleSendFromClientToServerMessage(object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        var message = (string)args[0]!;

        lock (_lock)
        {
             _sendFromClientToServerMessageCalls.Add(message);
        }

        if (SendFromClientToServerMessageHandler is not null)
        {
            return await SendFromClientToServerMessageHandler(message, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new global::System.InvalidOperationException("No behavior configured for SendFromClientToServerMessage.");
        }
        return default!;
    }

    private async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicReturn>> HandleSendFromClientToServerWithList(object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        var messages = (global::System.Collections.Generic.List<string>)args[0]!;

        lock (_lock)
        {
             _sendFromClientToServerWithListCalls.Add(messages);
        }

        if (SendFromClientToServerWithListHandler is not null)
        {
            return await SendFromClientToServerWithListHandler(messages, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new global::System.InvalidOperationException("No behavior configured for SendFromClientToServerWithList.");
        }
        return default!;
    }

    private async global::System.Threading.Tasks.Task HandleSendFromClientToServerWithoutReturnType(object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        var message = (string)args[0]!;

        lock (_lock)
        {
             _sendFromClientToServerWithoutReturnTypeCalls.Add(message);
        }

        if (SendFromClientToServerWithoutReturnTypeHandler is not null)
        {
            await SendFromClientToServerWithoutReturnTypeHandler(message, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new global::System.InvalidOperationException("No behavior configured for SendFromClientToServerWithoutReturnType.");
        }
        
    }

    private async global::System.Threading.Tasks.Task<bool> HandleSendFromClientToServerPrimitiveTypes(object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        var foo = (string)args[0]!;
        var bar = (int)args[1]!;

        lock (_lock)
        {
             _sendFromClientToServerPrimitiveTypesCalls.Add((foo, bar));
        }

        if (SendFromClientToServerPrimitiveTypesHandler is not null)
        {
            return await SendFromClientToServerPrimitiveTypesHandler(foo, bar, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new global::System.InvalidOperationException("No behavior configured for SendFromClientToServerPrimitiveTypes.");
        }
        return default!;
    }

    
    public async global::System.Threading.Tasks.Task SimulateOnSendFromServerToClientMessageAsync(global::SignalRGen.Clients.BasicMessage arg, global::System.Threading.CancellationToken ct = default)
    {var item = arg;lock (_lock) _onSendFromServerToClientMessageEvents.Add(item);
        await _onSendFromServerToClientMessageChannel.PublishAsync(item, ct);

        var handler = OnSendFromServerToClientMessage;
        if (handler is not null)
        {
            await handler.Invoke(arg);
        }
    }

    public async global::System.Threading.Tasks.Task<global::SignalRGen.Clients.BasicMessage> WaitForOnSendFromServerToClientMessageAsync(global::System.Threading.CancellationToken ct = default)
        => await _onSendFromServerToClientMessageChannel.WaitNextAsync(ct);

    
    public async global::System.Threading.Tasks.Task SimulateOnSendFromServerToClientWithListAsync(global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage> arg, global::System.Threading.CancellationToken ct = default)
    {var item = arg;lock (_lock) _onSendFromServerToClientWithListEvents.Add(item);
        await _onSendFromServerToClientWithListChannel.PublishAsync(item, ct);

        var handler = OnSendFromServerToClientWithList;
        if (handler is not null)
        {
            await handler.Invoke(arg);
        }
    }

    public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::SignalRGen.Clients.BasicMessage>> WaitForOnSendFromServerToClientWithListAsync(global::System.Threading.CancellationToken ct = default)
        => await _onSendFromServerToClientWithListChannel.WaitNextAsync(ct);

    
    public async global::System.Threading.Tasks.Task SimulateOnSendFromServerToClientPrimitiveTypesAsync(string arg1, int arg2, global::System.Threading.CancellationToken ct = default)
    {var item = (arg1, arg2);lock (_lock) _onSendFromServerToClientPrimitiveTypesEvents.Add(item);
        await _onSendFromServerToClientPrimitiveTypesChannel.PublishAsync(item, ct);

        var handler = OnSendFromServerToClientPrimitiveTypes;
        if (handler is not null)
        {
            await handler.Invoke(arg1, arg2);
        }
    }

    public async global::System.Threading.Tasks.Task<(string arg1, int arg2)> WaitForOnSendFromServerToClientPrimitiveTypesAsync(global::System.Threading.CancellationToken ct = default)
        => await _onSendFromServerToClientPrimitiveTypesChannel.WaitNextAsync(ct);

    public void ClearRecorded()
    {
        lock (_lock)
        {
            _sendFromClientToServerMessageCalls.Clear();
            _sendFromClientToServerWithListCalls.Clear();
            _sendFromClientToServerWithoutReturnTypeCalls.Clear();
            _sendFromClientToServerPrimitiveTypesCalls.Clear();

            _onSendFromServerToClientMessageEvents.Clear();
            _onSendFromServerToClientWithListEvents.Clear();
            _onSendFromServerToClientPrimitiveTypesEvents.Clear();
        }
        _onSendFromServerToClientMessageChannel.Reset();
        _onSendFromServerToClientWithListChannel.Reset();
        _onSendFromServerToClientPrimitiveTypesChannel.Reset();
    }
}