//HintName: FakeTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace SignalRGen.Clients.TestFakes;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

public sealed class FakeTestHubClient : SignalRGen.Clients.TestHubClient
{
    private readonly Lock _lock = new();

    public IReadOnlyList<(string rick, int age)> SendClientToServerNoReturnTypeCalls
    {
        get { lock (_lock) return _sendClientToServerNoReturnTypeCalls.ToList(); }
    }
    private readonly List<(string rick, int age)> _sendClientToServerNoReturnTypeCalls = new();
    
    public Func<string, int, CancellationToken, global::System.Threading.Tasks.Task>? SendClientToServerNoReturnTypeHandler { get; set; }
    
    
    public IReadOnlyList<(string morty, bool partOfMission)> SendClientToServerWithReturnTypeCalls
    {
        get { lock (_lock) return _sendClientToServerWithReturnTypeCalls.ToList(); }
    }
    private readonly List<(string morty, bool partOfMission)> _sendClientToServerWithReturnTypeCalls = new();
    
    public Func<string, bool, CancellationToken, global::System.Threading.Tasks.Task<string>>? SendClientToServerWithReturnTypeHandler { get; set; }
    
    
    /// <summary>
    /// When true, the fake client operates in strict mode:
    /// any unconfigured or unexpected invocation will throw an exception.
    /// Use to ensure tests explicitly define expected interactions.
    /// </summary>
    public bool Strict { get; set; }
    
    public FakeTestHubClient(
             Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration = null,
             Uri? baseHubUri = null,
             Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration = null)
             : base(hubConnectionBuilderConfiguration, baseHubUri ?? new Uri("http://localhost/"), httpConnectionOptionsConfiguration)
    {
    }
    
    protected override void RegisterHubMethods()
    {
    }
    
    public override Task StartAsync(
        Dictionary<string, string>? queryStrings = null,
        Dictionary<string, string>? headers = null,
        CancellationToken cancellationToken = default)
    {
        _hubConnection = new HubConnectionBuilder().WithUrl("http://localhost").Build();
        return Task.CompletedTask;
    }
    
    public override Task StopAsync(CancellationToken cancellationToken = default) => Task.CompletedTask;
    
    protected override async Task InvokeCoreAsync(string methodName, object?[] args, CancellationToken cancellationToken)
    {
        switch (methodName)
        {
            case "SendClientToServerNoReturnType":
                await HandleSendClientToServerNoReturnType(args, cancellationToken);
                return;
           
           default:
                if (Strict) throw new NotSupportedException($"Method '{methodName}' is not supported by the fake.");
                return;
        }
    }
    
    protected override async Task<TResult> InvokeCoreAsync<TResult>(string methodName, object?[] args, CancellationToken cancellationToken)
    {
        switch (methodName)
        {
            case "SendClientToServerWithReturnType":
                // We await the specific handler which returns the concrete type (e.g., string),
                // then cast it to TResult (which should be that same type).
                var result = await HandleSendClientToServerWithReturnType(args, cancellationToken);
                return (TResult)(object)result!;
           
           default:
                if (Strict) throw new NotSupportedException($"Method '{methodName}' is not supported by the fake.");
                return default!;
        }
    }
    
    private async global::System.Threading.Tasks.Task HandleSendClientToServerNoReturnType(object?[] args, CancellationToken cancellationToken)
    {
        // Unpack arguments
        var rick = (string)args[0]!;
        var age = (int)args[1]!;
    
        // Record invocation
        lock (_lock)
        {
             _sendClientToServerNoReturnTypeCalls.Add((rick, age));
        }
   
        // Invoke custom handler if present
        if (SendClientToServerNoReturnTypeHandler is not null)
        {
            await SendClientToServerNoReturnTypeHandler(rick, age, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new InvalidOperationException("No behavior configured for SendClientToServerNoReturnType.");
        }
        
    }
    
    private async global::System.Threading.Tasks.Task<string> HandleSendClientToServerWithReturnType(object?[] args, CancellationToken cancellationToken)
    {
        // Unpack arguments
        var morty = (string)args[0]!;
        var partOfMission = (bool)args[1]!;
    
        // Record invocation
        lock (_lock)
        {
             _sendClientToServerWithReturnTypeCalls.Add((morty, partOfMission));
        }
   
        // Invoke custom handler if present
        if (SendClientToServerWithReturnTypeHandler is not null)
        {
            return await SendClientToServerWithReturnTypeHandler(morty, partOfMission, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new InvalidOperationException("No behavior configured for SendClientToServerWithReturnType.");
        }
        return default!;
    }
}