//HintName: FakeTestHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace SignalRGen.Clients.TestFakes;


public sealed class FakeTestHubClient : SignalRGen.Clients.TestHubClient
{
    private readonly global::System.Threading.Lock _lock = new();

    public global::System.Collections.Generic.IReadOnlyList<(string rick, int age)> SendClientToServerNoReturnTypeCalls
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_sendClientToServerNoReturnTypeCalls); }
    }
    private readonly global::System.Collections.Generic.List<(string rick, int age)> _sendClientToServerNoReturnTypeCalls = new();
    
    public global::System.Func<string, int, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>? SendClientToServerNoReturnTypeHandler { get; set; }
    
    
    public global::System.Collections.Generic.IReadOnlyList<(string morty, bool partOfMission)> SendClientToServerWithReturnTypeCalls
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_sendClientToServerWithReturnTypeCalls); }
    }
    private readonly global::System.Collections.Generic.List<(string morty, bool partOfMission)> _sendClientToServerWithReturnTypeCalls = new();
    
    public global::System.Func<string, bool, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<string>>? SendClientToServerWithReturnTypeHandler { get; set; }
    
    


    public global::System.Collections.Generic.IReadOnlyList<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>> OnReceiveCustomTypeUpdateEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onReceiveCustomTypeUpdateEvents); }
    }
    private readonly global::System.Collections.Generic.List<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>> _onReceiveCustomTypeUpdateEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>> _onReceiveCustomTypeUpdateChannel = new();


    public global::System.Collections.Generic.IReadOnlyList<(string bar, int bass)> OnReceiveFooUpdateEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onReceiveFooUpdateEvents); }
    }
    private readonly global::System.Collections.Generic.List<(string bar, int bass)> _onReceiveFooUpdateEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<(string bar, int bass)> _onReceiveFooUpdateChannel = new();


    public global::System.Collections.Generic.IReadOnlyList<(string bazz, int buzz)> OnReceiveNormalTypeWithSpecificAttributeAppliedEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onReceiveNormalTypeWithSpecificAttributeAppliedEvents); }
    }
    private readonly global::System.Collections.Generic.List<(string bazz, int buzz)> _onReceiveNormalTypeWithSpecificAttributeAppliedEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<(string bazz, int buzz)> _onReceiveNormalTypeWithSpecificAttributeAppliedChannel = new();


    public global::System.Collections.Generic.IReadOnlyList<int> OnReceiveWithArbitraryAttributeEvents
    {
        get { lock (_lock) return global::System.Linq.Enumerable.ToList(_onReceiveWithArbitraryAttributeEvents); }
    }
    private readonly global::System.Collections.Generic.List<int> _onReceiveWithArbitraryAttributeEvents = new();
    private readonly global::SignalRGen.Testing.Abstractions.EventChannel<int> _onReceiveWithArbitraryAttributeChannel = new();

    /// <summary>
    /// When true, the fake client operates in strict mode:
    /// any unconfigured or unexpected invocation will throw an exception.
    /// Use to ensure tests explicitly define expected interactions.
    /// </summary>
    public bool Strict { get; set; }

    public FakeTestHubClient(
             global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration = null,
             global::System.Uri? baseHubUri = null,
             global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration = null)
             : base(hubConnectionBuilderConfiguration, baseHubUri ?? new global::System.Uri("http://localhost/"), httpConnectionOptionsConfiguration)
    {
    }

    protected override void RegisterHubMethods()
    {
    }

    public override global::System.Threading.Tasks.Task StartAsync(
        global::System.Collections.Generic.Dictionary<string, string>? queryStrings = null,
        global::System.Collections.Generic.Dictionary<string, string>? headers = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var builder = new global::Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder();
        
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilderHttpExtensions
                                               .WithUrl(builder, "http://localhost");
        
        _hubConnection = builder.Build();
        
        return global::System.Threading.Tasks.Task.CompletedTask;
    }

    public override global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::System.Threading.Tasks.Task.CompletedTask;

    protected override async global::System.Threading.Tasks.Task InvokeCoreAsync(string methodName, object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        switch (methodName)
        {
            case "SendClientToServerNoReturnType":
                await HandleSendClientToServerNoReturnType(args, cancellationToken);
                return;
       
           default:
                if (Strict) throw new global::System.NotSupportedException($"Method '{methodName}' is not supported by the fake.");
                return;
        }
    }

    protected override async global::System.Threading.Tasks.Task<TResult> InvokeCoreAsync<TResult>(string methodName, object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        switch (methodName)
        {
            case "SendClientToServerWithReturnType":
                var resultSendClientToServerWithReturnType = await HandleSendClientToServerWithReturnType(args, cancellationToken);
                return (TResult)(object)resultSendClientToServerWithReturnType!;
       
           default:
                if (Strict) throw new global::System.NotSupportedException($"Method '{methodName}' is not supported by the fake.");
                return default!;
        }
    }

    private async global::System.Threading.Tasks.Task HandleSendClientToServerNoReturnType(object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        var rick = (string)args[0]!;
        var age = (int)args[1]!;

        lock (_lock)
        {
             _sendClientToServerNoReturnTypeCalls.Add((rick, age));
        }

        if (SendClientToServerNoReturnTypeHandler is not null)
        {
            await SendClientToServerNoReturnTypeHandler(rick, age, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new global::System.InvalidOperationException("No behavior configured for SendClientToServerNoReturnType.");
        }
        
    }

    private async global::System.Threading.Tasks.Task<string> HandleSendClientToServerWithReturnType(object?[] args, global::System.Threading.CancellationToken cancellationToken)
    {
        var morty = (string)args[0]!;
        var partOfMission = (bool)args[1]!;

        lock (_lock)
        {
             _sendClientToServerWithReturnTypeCalls.Add((morty, partOfMission));
        }

        if (SendClientToServerWithReturnTypeHandler is not null)
        {
            return await SendClientToServerWithReturnTypeHandler(morty, partOfMission, cancellationToken
            );
        }
        else if (Strict)
        {
            throw new global::System.InvalidOperationException("No behavior configured for SendClientToServerWithReturnType.");
        }
        return default!;
    }

    
    public async global::System.Threading.Tasks.Task SimulateOnReceiveCustomTypeUpdateAsync(IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> customTypes, global::System.Threading.CancellationToken ct = default)
    {var item = customTypes;lock (_lock) _onReceiveCustomTypeUpdateEvents.Add(item);
        await _onReceiveCustomTypeUpdateChannel.PublishAsync(item, ct);

        var handler = OnReceiveCustomTypeUpdate;
        if (handler is not null)
        {
            await handler.Invoke(customTypes);
        }
    }

    public async global::System.Threading.Tasks.Task<IEnumerable<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>> WaitForOnReceiveCustomTypeUpdateAsync(global::System.Threading.CancellationToken ct = default)
        => await _onReceiveCustomTypeUpdateChannel.WaitNextAsync(ct);

    
    public async global::System.Threading.Tasks.Task SimulateOnReceiveFooUpdateAsync(string bar, int bass, global::System.Threading.CancellationToken ct = default)
    {var item = (bar, bass);lock (_lock) _onReceiveFooUpdateEvents.Add(item);
        await _onReceiveFooUpdateChannel.PublishAsync(item, ct);

        var handler = OnReceiveFooUpdate;
        if (handler is not null)
        {
            await handler.Invoke(bar, bass);
        }
    }

    public async global::System.Threading.Tasks.Task<(string bar, int bass)> WaitForOnReceiveFooUpdateAsync(global::System.Threading.CancellationToken ct = default)
        => await _onReceiveFooUpdateChannel.WaitNextAsync(ct);

    
    public async global::System.Threading.Tasks.Task SimulateOnReceiveNormalTypeWithSpecificAttributeAppliedAsync(string bazz, int buzz, global::System.Threading.CancellationToken ct = default)
    {var item = (bazz, buzz);lock (_lock) _onReceiveNormalTypeWithSpecificAttributeAppliedEvents.Add(item);
        await _onReceiveNormalTypeWithSpecificAttributeAppliedChannel.PublishAsync(item, ct);

        var handler = OnReceiveNormalTypeWithSpecificAttributeApplied;
        if (handler is not null)
        {
            await handler.Invoke(bazz, buzz);
        }
    }

    public async global::System.Threading.Tasks.Task<(string bazz, int buzz)> WaitForOnReceiveNormalTypeWithSpecificAttributeAppliedAsync(global::System.Threading.CancellationToken ct = default)
        => await _onReceiveNormalTypeWithSpecificAttributeAppliedChannel.WaitNextAsync(ct);

    
    public async global::System.Threading.Tasks.Task SimulateOnReceiveWithArbitraryAttributeAsync(int blub, global::System.Threading.CancellationToken ct = default)
    {var item = blub;lock (_lock) _onReceiveWithArbitraryAttributeEvents.Add(item);
        await _onReceiveWithArbitraryAttributeChannel.PublishAsync(item, ct);

        var handler = OnReceiveWithArbitraryAttribute;
        if (handler is not null)
        {
            await handler.Invoke(blub);
        }
    }

    public async global::System.Threading.Tasks.Task<int> WaitForOnReceiveWithArbitraryAttributeAsync(global::System.Threading.CancellationToken ct = default)
        => await _onReceiveWithArbitraryAttributeChannel.WaitNextAsync(ct);

    public void ClearRecorded()
    {
        lock (_lock)
        {
            _sendClientToServerNoReturnTypeCalls.Clear();
            _sendClientToServerWithReturnTypeCalls.Clear();

            _onReceiveCustomTypeUpdateEvents.Clear();
            _onReceiveFooUpdateEvents.Clear();
            _onReceiveNormalTypeWithSpecificAttributeAppliedEvents.Clear();
            _onReceiveWithArbitraryAttributeEvents.Clear();
        }
        _onReceiveCustomTypeUpdateChannel.Reset();
        _onReceiveFooUpdateChannel.Reset();
        _onReceiveNormalTypeWithSpecificAttributeAppliedChannel.Reset();
        _onReceiveWithArbitraryAttributeChannel.Reset();
    }
}