//HintName: ComplexNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IComplexNotificationHubClient"/> interface.
/// </summary>
public class ComplexNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "complex-notifications";
    public ComplexNotificationHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveUserList of the <see cref = "global::SignalRGen.Clients.IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>, global::System.Threading.Tasks.Task>? OnReceiveUserList = default;
    private global::System.Threading.Tasks.Task ReceiveUserListHandler(List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto> users)
    {
        return OnReceiveUserList?.Invoke(users) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveDataUpdate of the <see cref = "global::SignalRGen.Clients.IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<Dictionary<string, int>, global::System.Threading.Tasks.Task>? OnReceiveDataUpdate = default;
    private global::System.Threading.Tasks.Task ReceiveDataUpdateHandler(Dictionary<string, int> metrics)
    {
        return OnReceiveDataUpdate?.Invoke(metrics) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableData of the <see cref = "global::SignalRGen.Clients.IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<string, int?, global::System.Threading.Tasks.Task>? OnReceiveNullableData = default;
    private global::System.Threading.Tasks.Task ReceiveNullableDataHandler(string nullableMessage, int? nullableCount)
    {
        return OnReceiveNullableData?.Invoke(nullableMessage, nullableCount) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveArrayData of the <see cref = "global::SignalRGen.Clients.IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<string[], global::SignalRGen.Generator.Tests.TestData.CustomTypeDto[], global::System.Threading.Tasks.Task>? OnReceiveArrayData = default;
    private global::System.Threading.Tasks.Task ReceiveArrayDataHandler(string[] messages, global::SignalRGen.Generator.Tests.TestData.CustomTypeDto[] dtos)
    {
        return OnReceiveArrayData?.Invoke(messages, dtos) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveTupleData of the <see cref = "global::SignalRGen.Clients.IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<(string name, int value), global::System.Threading.Tasks.Task>? OnReceiveTupleData = default;
    private global::System.Threading.Tasks.Task ReceiveTupleDataHandler((string name, int value) tupleData)
    {
        return OnReceiveTupleData?.Invoke(tupleData) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<List<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>>(_hubConnection, "ReceiveUserList", ReceiveUserListHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<Dictionary<string, int>>(_hubConnection, "ReceiveDataUpdate", ReceiveDataUpdateHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int?>(_hubConnection, "ReceiveNullableData", ReceiveNullableDataHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string[], global::SignalRGen.Generator.Tests.TestData.CustomTypeDto[]>(_hubConnection, "ReceiveArrayData", ReceiveArrayDataHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<(string name, int value)>(_hubConnection, "ReceiveTupleData", ReceiveTupleDataHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}