//HintName: ParameterlessNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.IParameterlessNotificationHubClient"/> interface.
/// </summary>
public class ParameterlessNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "parameterless-notifications";
    public ParameterlessNotificationHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveHeartbeat of the <see cref = "global::SignalRGen.Clients.IParameterlessNotificationHubClient"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveHeartbeatDelegate();
    public ReceiveHeartbeatDelegate? OnReceiveHeartbeat = default;
    
    private global::System.Threading.Tasks.Task ReceiveHeartbeatHandler()
    {
        return OnReceiveHeartbeat?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveRefreshSignal of the <see cref = "global::SignalRGen.Clients.IParameterlessNotificationHubClient"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveRefreshSignalDelegate();
    public ReceiveRefreshSignalDelegate? OnReceiveRefreshSignal = default;
    
    private global::System.Threading.Tasks.Task ReceiveRefreshSignalHandler()
    {
        return OnReceiveRefreshSignal?.Invoke() ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "ReceiveHeartbeat", ReceiveHeartbeatHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On(_hubConnection, "ReceiveRefreshSignal", ReceiveRefreshSignalHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}