//HintName: ParameterlessNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IParameterlessNotificationHubClient"/> interface.
/// </summary>
public class ParameterlessNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "parameterless-notifications";
    public ParameterlessNotificationHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveHeartbeat of the <see cref = "IParameterlessNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<Task>? OnReceiveHeartbeat = default;
    private Task ReceiveHeartbeatHandler()
    {
        return OnReceiveHeartbeat?.Invoke() ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveRefreshSignal of the <see cref = "IParameterlessNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<Task>? OnReceiveRefreshSignal = default;
    private Task ReceiveRefreshSignalHandler()
    {
        return OnReceiveRefreshSignal?.Invoke() ?? Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On("ReceiveHeartbeat", ReceiveHeartbeatHandler);
	    _hubConnection?.On("ReceiveRefreshSignal", ReceiveRefreshSignalHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}