//HintName: SignalRClientServiceRegistration.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Generator.Client.Extensions.DependencyInjection;

public static class SignalRClientServiceRegistration
{
    /// <summary>
    /// Creates the base configuration for all registered Hubs. The Hubs you want to use must be registered with the appropriate `With{...}` call.
    /// </summary>
    /// <param name = "services">The services available in the application.</param>
    /// <param name = "generalConfiguration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection{T}"/> to register the specified Hub.</returns>
    public static global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase> AddSignalRHubs(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, Action<global::SignalRGen.Abstractions.Configuration.SignalROptions> generalConfiguration)
    {
        ArgumentNullException.ThrowIfNull(generalConfiguration);
        var config = new global::SignalRGen.Abstractions.Configuration.SignalROptions();
        generalConfiguration.Invoke(config);
        return new global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase>(services, config);
    }

    /// <summary>
    /// Registers the <see cref = "ParameterlessNotificationHubClient"/> in the <see cref = "global::Microsoft.Extensions.DependencyInjection.ServiceCollection"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// By default the <see cref = "ParameterlessNotificationHubClient"/> is registered with <see cref = "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime"/> singleton.
    /// </para>
    /// If no <see cref = "global::Microsoft.AspNetCore.SignalR.Client.IRetryPolicy"/> is configured for the <see cref = "global::Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder"/> a default retry policy will be used.
    /// <list type="bullet">
    ///     <item>
    ///         Every second - 10 attempts
    ///     </item>
    ///     <item>
    ///         Every 3 seconds - 5 attempts
    ///     </item>
    ///     <item>
    ///         Every 10 seconds - 2 attempts
    ///     </item>
    /// </list>
    /// </remarks>
    /// <param name = "services">The <see cref = "global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection{T}"/> to register the Hub.</param>
    /// <param name = "configuration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection{T}"/> to register additional Hubs.</returns>
    public static global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase> WithParameterlessNotificationHubClient(this global::SignalRGen.Abstractions.Configuration.SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase> services, Action<global::SignalRGen.Abstractions.Configuration.HubClientOptions>? configuration = null)
    {
        ArgumentNullException.ThrowIfNull(services);
        var config = new global::SignalRGen.Abstractions.Configuration.HubClientOptions();
        configuration?.Invoke(config);
        services.Services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(ParameterlessNotificationHubClient), factory: _ =>
        {
            return new ParameterlessNotificationHubClient(config.HubConnectionBuilderConfiguration,
            new Uri(services.GeneralConfiguration.HubBaseUri, ParameterlessNotificationHubClient.HubUri),
            config.HttpConnectionOptionsConfiguration!);
        }, config.HubClientLifetime));
        return services;
    }
}