//HintName: MultiLevelNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IMultiLevelNotificationHubClient"/> interface.
/// </summary>
public class MultiLevelNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "multi-level-notifications";
    public MultiLevelNotificationHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveTopNotification of the <see cref = "IMultiLevelNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<SignalRGen.Generator.Tests.TestData.CustomTypeDto, Task>? OnReceiveTopNotification = default;
    private Task ReceiveTopNotificationHandler(SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveTopNotification?.Invoke(dto) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveMidNotification of the <see cref = "IMultiLevelNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<int, Task>? OnReceiveMidNotification = default;
    private Task ReceiveMidNotificationHandler(int value)
    {
        return OnReceiveMidNotification?.Invoke(value) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveBaseNotification of the <see cref = "IMultiLevelNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<string, Task>? OnReceiveBaseNotification = default;
    private Task ReceiveBaseNotificationHandler(string message)
    {
        return OnReceiveBaseNotification?.Invoke(message) ?? Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<SignalRGen.Generator.Tests.TestData.CustomTypeDto>("ReceiveTopNotification", ReceiveTopNotificationHandler);
	    _hubConnection?.On<int>("ReceiveMidNotification", ReceiveMidNotificationHandler);
	    _hubConnection?.On<string>("ReceiveBaseNotification", ReceiveBaseNotificationHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}