//HintName: MultiLevelNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IMultiLevelNotificationHubClient"/> interface.
/// </summary>
public class MultiLevelNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "multi-level-notifications";
    public MultiLevelNotificationHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveTopNotification of the <see cref = "global::SignalRGen.Clients.IMultiLevelNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto, global::System.Threading.Tasks.Task>? OnReceiveTopNotification = default;
    private global::System.Threading.Tasks.Task ReceiveTopNotificationHandler(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveTopNotification?.Invoke(dto) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveMidNotification of the <see cref = "global::SignalRGen.Clients.IMultiLevelNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<int, global::System.Threading.Tasks.Task>? OnReceiveMidNotification = default;
    private global::System.Threading.Tasks.Task ReceiveMidNotificationHandler(int value)
    {
        return OnReceiveMidNotification?.Invoke(value) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveBaseNotification of the <see cref = "global::SignalRGen.Clients.IMultiLevelNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<string, global::System.Threading.Tasks.Task>? OnReceiveBaseNotification = default;
    private global::System.Threading.Tasks.Task ReceiveBaseNotificationHandler(string message)
    {
        return OnReceiveBaseNotification?.Invoke(message) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>(_hubConnection, "ReceiveTopNotification", ReceiveTopNotificationHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<int>(_hubConnection, "ReceiveMidNotification", ReceiveMidNotificationHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string>(_hubConnection, "ReceiveBaseNotification", ReceiveBaseNotificationHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}