//HintName: ExtendedNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.IExtendedNotificationHubClient"/> interface.
/// </summary>
public class ExtendedNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "extended-notifications";
    public ExtendedNotificationHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveExtendedNotification of the <see cref = "global::SignalRGen.Clients.IExtendedNotificationHubClient"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveExtendedNotificationDelegate(string message, int priority);
    public ReceiveExtendedNotificationDelegate? OnReceiveExtendedNotification = default;
    
    private global::System.Threading.Tasks.Task ReceiveExtendedNotificationHandler(string message, int priority)
    {
        return OnReceiveExtendedNotification?.Invoke(message, priority) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeNotification of the <see cref = "global::SignalRGen.Clients.IExtendedNotificationHubClient"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveCustomTypeNotificationDelegate(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto dto);
    public ReceiveCustomTypeNotificationDelegate? OnReceiveCustomTypeNotification = default;
    
    private global::System.Threading.Tasks.Task ReceiveCustomTypeNotificationHandler(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveCustomTypeNotification?.Invoke(dto) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveBaseNotification of the <see cref = "global::SignalRGen.Clients.IExtendedNotificationHubClient"/> gets invoked.
    /// </summary>
    public delegate global::System.Threading.Tasks.Task ReceiveBaseNotificationDelegate(string message);
    public ReceiveBaseNotificationDelegate? OnReceiveBaseNotification = default;
    
    private global::System.Threading.Tasks.Task ReceiveBaseNotificationHandler(string message)
    {
        return OnReceiveBaseNotification?.Invoke(message) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "ReceiveExtendedNotification", ReceiveExtendedNotificationHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>(_hubConnection, "ReceiveCustomTypeNotification", ReceiveCustomTypeNotificationHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string>(_hubConnection, "ReceiveBaseNotification", ReceiveBaseNotificationHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}