//HintName: NestedNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients.Nested;

/// <summary>
/// Represents a HubClient for the <see cref = "INestedNotificationHubClient"/> interface.
/// </summary>
public class NestedNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "nested-notifications";
    public NestedNotificationHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedNotification of the <see cref = "global::SignalRGen.Clients.Nested.INestedNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<string, global::System.Threading.Tasks.Task>? OnReceiveNestedNotification = default;
    private global::System.Threading.Tasks.Task ReceiveNestedNotificationHandler(string message)
    {
        return OnReceiveNestedNotification?.Invoke(message) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedData of the <see cref = "global::SignalRGen.Clients.Nested.INestedNotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto, global::System.Threading.Tasks.Task>? OnReceiveNestedData = default;
    private global::System.Threading.Tasks.Task ReceiveNestedDataHandler(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveNestedData?.Invoke(dto) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string>(_hubConnection, "ReceiveNestedNotification", ReceiveNestedNotificationHandler);
	    global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>(_hubConnection, "ReceiveNestedData", ReceiveNestedDataHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}