//HintName: SignalRClientServiceRegistration.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SignalRGen.Clients;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.DependencyInjection;
using SignalRGen.Abstractions.Configuration;

#nullable enable

namespace SignalRGen.Generator.Client.Extensions.DependencyInjection;

public static class SignalRClientServiceRegistration
{
    /// <summary>
    /// Creates the base configuration for all registered Hubs. The Hubs you want to use must be registered with the appropriate `With{...}` call.
    /// </summary>
    /// <param name = "services">The services available in the application.</param>
    /// <param name = "generalConfiguration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "SignalRHubServiceCollection{T}"/> to register the specified Hub.</returns>
    public static SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase> AddSignalRHubs(this IServiceCollection services, Action<SignalROptions> generalConfiguration)
    {
        ArgumentNullException.ThrowIfNull(generalConfiguration);
        var config = new SignalROptions();
        generalConfiguration.Invoke(config);
        return new SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase>(services, config);
    }

    /// <summary>
    /// Registers the <see cref = "MultiLevelNotificationHubClient"/> in the <see cref = "ServiceCollection"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// By default the <see cref = "MultiLevelNotificationHubClient"/> is registered with <see cref = "ServiceLifetime"/> singleton.
    /// </para>
    /// If no <see cref = "IRetryPolicy"/> is configured for the <see cref = "HubConnectionBuilder"/> a default retry policy will be used.
    /// <list type="bullet">
    ///     <item>
    ///         Every second - 10 attempts
    ///     </item>
    ///     <item>
    ///         Every 3 seconds - 5 attempts
    ///     </item>
    ///     <item>
    ///         Every 10 seconds - 2 attempts
    ///     </item>
    /// </list>
    /// </remarks>
    /// <param name = "services">The <see cref = "SignalRHubServiceCollection{T}"/> to register the Hub.</param>
    /// <param name = "configuration">An action used to configure the provided options.</param>
    /// <returns>The <see cref = "SignalRHubServiceCollection{T}"/> to register additional Hubs.</returns>
    public static SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase> WithMultiLevelNotificationHubClient(this SignalRHubServiceCollection<SignalRGen.Generator.HubClientBase> services, Action<HubClientOptions>? configuration = null)
    {
        ArgumentNullException.ThrowIfNull(services);
        var config = new HubClientOptions();
        configuration?.Invoke(config);
        services.Services.Add(new ServiceDescriptor(typeof(MultiLevelNotificationHubClient), factory: _ =>
        {
            return new MultiLevelNotificationHubClient(config.HubConnectionBuilderConfiguration,
            new Uri(services.GeneralConfiguration.HubBaseUri, MultiLevelNotificationHubClient.HubUri),
            config.HttpConnectionOptionsConfiguration!);
        }, config.HubClientLifetime));
        return services;
    }
}