//HintName: NestedNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients.Nested;

/// <summary>
/// Represents a HubClient for the <see cref = "INestedNotificationHubClient"/> interface.
/// </summary>
public class NestedNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "nested-notifications";
    public NestedNotificationHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedNotification of the <see cref = "INestedNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<string, Task>? OnReceiveNestedNotification = default;
    private Task ReceiveNestedNotificationHandler(string message)
    {
        return OnReceiveNestedNotification?.Invoke(message) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNestedData of the <see cref = "INestedNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<SignalRGen.Generator.Tests.TestData.CustomTypeDto, Task>? OnReceiveNestedData = default;
    private Task ReceiveNestedDataHandler(SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveNestedData?.Invoke(dto) ?? Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string>("ReceiveNestedNotification", ReceiveNestedNotificationHandler);
	    _hubConnection?.On<SignalRGen.Generator.Tests.TestData.CustomTypeDto>("ReceiveNestedData", ReceiveNestedDataHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}