//HintName: ComplexNotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "IComplexNotificationHubClient"/> interface.
/// </summary>
public class ComplexNotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "complex-notifications";
    public ComplexNotificationHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveUserList of the <see cref = "IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<List<SignalRGen.Generator.Tests.TestData.CustomTypeDto>, Task>? OnReceiveUserList = default;
    private Task ReceiveUserListHandler(List<SignalRGen.Generator.Tests.TestData.CustomTypeDto> users)
    {
        return OnReceiveUserList?.Invoke(users) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveDataUpdate of the <see cref = "IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<Dictionary<string, int>, Task>? OnReceiveDataUpdate = default;
    private Task ReceiveDataUpdateHandler(Dictionary<string, int> metrics)
    {
        return OnReceiveDataUpdate?.Invoke(metrics) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveNullableData of the <see cref = "IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<string?, int?, Task>? OnReceiveNullableData = default;
    private Task ReceiveNullableDataHandler(string? nullableMessage, int? nullableCount)
    {
        return OnReceiveNullableData?.Invoke(nullableMessage, nullableCount) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveArrayData of the <see cref = "IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<string[], SignalRGen.Generator.Tests.TestData.CustomTypeDto[], Task>? OnReceiveArrayData = default;
    private Task ReceiveArrayDataHandler(string[] messages, SignalRGen.Generator.Tests.TestData.CustomTypeDto[] dtos)
    {
        return OnReceiveArrayData?.Invoke(messages, dtos) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveTupleData of the <see cref = "IComplexNotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<(string name, int value), Task>? OnReceiveTupleData = default;
    private Task ReceiveTupleDataHandler((string name, int value) tupleData)
    {
        return OnReceiveTupleData?.Invoke(tupleData) ?? Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<List<SignalRGen.Generator.Tests.TestData.CustomTypeDto>>("ReceiveUserList", ReceiveUserListHandler);
	    _hubConnection?.On<Dictionary<string, int>>("ReceiveDataUpdate", ReceiveDataUpdateHandler);
	    _hubConnection?.On<string?, int?>("ReceiveNullableData", ReceiveNullableDataHandler);
	    _hubConnection?.On<string[], SignalRGen.Generator.Tests.TestData.CustomTypeDto[]>("ReceiveArrayData", ReceiveArrayDataHandler);
	    _hubConnection?.On<(string name, int value)>("ReceiveTupleData", ReceiveTupleDataHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}