//HintName: NotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "global::SignalRGen.Clients.INotificationHubClient"/> interface.
/// </summary>
public class NotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "notifications";
    public NotificationHubClient(
        global::System.Action<global::Microsoft.AspNetCore.SignalR.Client.IHubConnectionBuilder>? hubConnectionBuilderConfiguration,
        global::System.Uri baseHubUri,
        global::System.Action<global::Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionOptions>? httpConnectionOptionsConfiguration)
        : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveNotification of the <see cref = "global::SignalRGen.Clients.INotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<string, string, global::System.Threading.Tasks.Task>? OnReceiveNotification = default;
    private global::System.Threading.Tasks.Task ReceiveNotificationHandler(string message, string type)
    {
        return OnReceiveNotification?.Invoke(message, type) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveAlert of the <see cref = "global::SignalRGen.Clients.INotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<string, int, global::System.Threading.Tasks.Task>? OnReceiveAlert = default;
    private global::System.Threading.Tasks.Task ReceiveAlertHandler(string alertMessage, int severity)
    {
        return OnReceiveAlert?.Invoke(alertMessage, severity) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeUpdate of the <see cref = "global::SignalRGen.Clients.INotificationHubClient"/> gets invoked.
    /// </summary>
    public global::System.Func<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto, global::System.Threading.Tasks.Task>? OnReceiveCustomTypeUpdate = default;
    private global::System.Threading.Tasks.Task ReceiveCustomTypeUpdateHandler(global::SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveCustomTypeUpdate?.Invoke(dto) ?? global::System.Threading.Tasks.Task.CompletedTask;
    }

    
    protected override void RegisterHubMethods()
    {
        if (_hubConnection is null)
        {
            return;
        }
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, string>(_hubConnection, "ReceiveNotification", ReceiveNotificationHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<string, int>(_hubConnection, "ReceiveAlert", ReceiveAlertHandler);
        global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.On<global::SignalRGen.Generator.Tests.TestData.CustomTypeDto>(_hubConnection, "ReceiveCustomTypeUpdate", ReceiveCustomTypeUpdateHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new global::System.InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}