//HintName: NotificationHubClient.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using SignalRGen.Abstractions;
using SignalRGen.Abstractions.Attributes;
using SignalRGen.Generator.Tests.TestData;
using System;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Connections.Client;

#nullable enable

namespace SignalRGen.Clients;

/// <summary>
/// Represents a HubClient for the <see cref = "INotificationHubClient"/> interface.
/// </summary>
public class NotificationHubClient : HubClientBase
{
    public static string HubUri { get; } = "notifications";
    public NotificationHubClient(Action<IHubConnectionBuilder>? hubConnectionBuilderConfiguration, Uri baseHubUri, Action<HttpConnectionOptions>? httpConnectionOptionsConfiguration) : base(hubConnectionBuilderConfiguration, baseHubUri, httpConnectionOptionsConfiguration)
    {
    }
    
    /// <summary>
    /// Is invoked whenever the client method ReceiveNotification of the <see cref = "INotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<string, string, Task>? OnReceiveNotification = default;
    private Task ReceiveNotificationHandler(string message, string type)
    {
        return OnReceiveNotification?.Invoke(message, type) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveAlert of the <see cref = "INotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<string, int, Task>? OnReceiveAlert = default;
    private Task ReceiveAlertHandler(string alertMessage, int severity)
    {
        return OnReceiveAlert?.Invoke(alertMessage, severity) ?? Task.CompletedTask;
    }
    /// <summary>
    /// Is invoked whenever the client method ReceiveCustomTypeUpdate of the <see cref = "INotificationHubClient"/> gets invoked.
    /// </summary>
    public Func<SignalRGen.Generator.Tests.TestData.CustomTypeDto, Task>? OnReceiveCustomTypeUpdate = default;
    private Task ReceiveCustomTypeUpdateHandler(SignalRGen.Generator.Tests.TestData.CustomTypeDto dto)
    {
        return OnReceiveCustomTypeUpdate?.Invoke(dto) ?? Task.CompletedTask;
    }



    
    protected override void RegisterHubMethods()
    {
        _hubConnection?.On<string, string>("ReceiveNotification", ReceiveNotificationHandler);
	    _hubConnection?.On<string, int>("ReceiveAlert", ReceiveAlertHandler);
	    _hubConnection?.On<SignalRGen.Generator.Tests.TestData.CustomTypeDto>("ReceiveCustomTypeUpdate", ReceiveCustomTypeUpdateHandler);
    }
    
    private void ValidateHubConnection()
    {
        if (_hubConnection is null)
        {
            throw new InvalidOperationException("The HubConnection is not started! Call `StartAsync` before initiating any actions.");
        }
    }
}